// Common tag suggestions used across recipes
export const tagSuggestions: string[] = [
  "High-Protein",
  "Low-Carb",
  "Glutenfrei",
  "Vegetarisch",
  "Vegan-möglich",
  "Mealprep",
  "Mealprep-tauglich",
  "Schnell",
  "Quick",
  "5 Minuten",
  "15 Minuten",
  "Single-Serve",
  "Familienküche",
  "Sonntag-Backen",
  "Trend",
  "Frühstück",
  "Snack",
  "Dessert",
  "No-Bake",
  "TK",
  "On-the-Go",
  "Asia",
  "Mediterran",
  "Curry",
  "Volumen",
  "Suppe",
  "Salat",
  "Bowl",
  "Handheld",
  "3 Zutaten",
  "Ohne Mehl",
  "Versteckte Bohnen",
  "Pistazien",
  "Sommer",
  "Frühlingsgefühl",
  "Omega-3",
];
