// Cached pack-forewords. Mirrors the pattern of lib/recipe-micros.ts —
// a static map keyed by pack slug, populated by a generation script and
// committed to git. The render pipeline reads from this cache instead
// of calling Gemini at render-time, so PDFs render in a few hundred
// milliseconds rather than tens of seconds.
//
// Re-generieren: `npx tsx scripts/generate-foreword-assets.ts <packSlug>`
// (single pack) oder `npx tsx scripts/generate-foreword-assets.ts --all`
// (alle Packs neu). Die Re-generation ist nicht-destruktiv: bestehende
// Einträge werden ueberschrieben (mit --force), andere bleiben unangetastet.
//
// Auto-generated by Gemini, then hand-polished — Bienes Tonalität ist
// nuanced (warm, persoenlich, nie generisch). Gemini hat eine Tendenz
// jede Karte mit demselben Greeting zu starten; das Polishing fuehrt
// pack-spezifische Greetings ein, die dem jeweiligen Layout passen
// (z.B. "Hi." kurz fuer Minimal-Display-Anker, "Komm rein." warm fuer
// Editorial-Magazin-Stil).

import type { PackForewordContent } from "./ai/generate-foreword";

export const packForewords: Record<string, PackForewordContent> = {
  "bienes-backwelt": {
    greeting: "Hi, ich bin Biene.",
    story:
      "Backen ist meine Paradedisziplin. Hier sind 10 meiner liebsten Werke aus den Reels — Schoko-Biskuitrolle, Cheesecake, Erdbeer-Kuppeltorte. Alle ohne zugesetzten Zucker, alle WPF-tauglich, alle so, wie ich sie selbst in meiner Küche backe, wenn ich Lust auf etwas Süßes habe.",
    signoff: "Schnapp dir einen Kaffee und blätter durch.",
  },
  "volumen-wunder": {
    greeting: "Hey, da bin ich.",
    story:
      'Diese Rezepte sind meine Antwort auf „aber dann hab ich doch nichts auf dem Teller". XL-Wraps, die cremige Zucchini-Frittata, mein viraler lebensverändernder Salat — alles unter 450 kcal, alles kein bisschen weniger sättigend als deine alten Lieblinge. Du wirst überrascht sein, wie viel Volumen hier auf deinen Teller kommt.',
    signoff: "Probier's aus, du wirst nicht hungrig vom Tisch aufstehen.",
  },
  "blitz-snacks": {
    greeting: "Hi du.",
    story:
      "Diese fünf Snacks habe ich nicht für die Kamera erfunden — sie sind tatsächlich aus den Momenten entstanden, in denen ich um 16 Uhr Heißhunger auf was Süßes hatte und keine Lust, das halbe Kuchen-Setup aufzubauen. Fluffiger Kaiserschmarrn, der wirklich in zehn Minuten auf dem Teller liegt. Cremige Frozen Cups, die ich Sonntagabend vorbereite, bevor mir wieder einfällt, dass ich Mittwoch was Süßes brauche. Zuckerfreie Marzipan-Kugeln, die ich für die Hand-am-Schreibtisch-Naschmomente entwickelt habe. Alle WPF-tauglich, alle mit echtem Protein-Anteil, alle so simpel, dass du sie auch nach einem 12-Stunden-Tag noch fertigkriegst, ohne dass die Küche aussieht wie nach einer Backstunde.",
    signoff: "Drück dich, dein Kaiserschmarrn wartet schon.",
  },
  "meal-prep-heroes": {
    greeting: "Schön, dass du planst.",
    story:
      "Mealprep ist mein Wochenplan, nicht mein Hobby. Hier sind 8 meiner viralen Mealprep-Hits aus den Reels: süße Löffelkuchen, herzhafte Lasagne in der Glas-Dose, Spekulatius-Tiramisu. Alle für 2 bis 4 Tage haltbar, alle bürotauglich, alle bewusst leise im Geschmack — damit du sie auch am Donnerstag noch gerne isst.",
    signoff: "Sonntag vorkochen, eine Woche entspannt sein.",
  },
  "feierabend-klassiker": {
    greeting: "Komm rein, mach's dir gemütlich.",
    story:
      "Wenn der Tag lang war, will ich nicht zwei Stunden in der Küche stehen — und auch nicht auf was verzichten. Hier sind meine 7 viralen Feierabend-Helden: Käse-Nudeln, Cheeseburger-Auflauf, Cloud Wrap. Alle mit 30 bis 55 g Protein pro Portion, alle echte Sattmacher, alle so umgebaut, dass sie ins WPF passen.",
    signoff: "Schmeckt nach Feierabend. Versprochen.",
  },
};

export function getPackForeword(packSlug: string): PackForewordContent | null {
  return packForewords[packSlug] ?? null;
}
