// Auto-generated by scripts/generate-recipe-heroes.ts.
// Hero image URL per recipe slug. JPEG files live in
// public/brands/<brand>/heroes/<slug>.jpg and are served as static assets.
// Manual edits will be overwritten on the next batch run.
//
// Re-generate (one recipe):  npx tsx scripts/generate-recipe-heroes.ts <slug>
// Re-generate (all):          npx tsx scripts/generate-recipe-heroes.ts --force

export const recipeHeroes: Record<string, string> = {
  "banana-bread-pudding": "/brands/biene/heroes/banana-bread-pudding.jpg",
  "beeren-cookie-crumble": "/brands/biene/heroes/beeren-cookie-crumble.jpg",
  "blaubeer-cheesecake-no-bake": "/brands/biene/heroes/blaubeer-cheesecake-no-bake.jpg",
  "blech-pasta": "/brands/biene/heroes/blech-pasta.jpg",
  "blitz-cheeseburger-auflauf": "/brands/biene/heroes/blitz-cheeseburger-auflauf.jpg",
  "drei-zutaten-eisbowl": "/brands/biene/heroes/drei-zutaten-eisbowl.jpg",
  "einfachstes-protein-brot": "/brands/biene/heroes/einfachstes-protein-brot.jpg",
  "erdbeer-biscuit-pudding-kuchen": "/brands/biene/heroes/erdbeer-biscuit-pudding-kuchen.jpg",
  "erdbeer-kuppeltorte": "/brands/biene/heroes/erdbeer-kuppeltorte.jpg",
  "erdbeer-loeffelkuchen": "/brands/biene/heroes/erdbeer-loeffelkuchen.jpg",
  "feta-haehnchen-blech": "/brands/biene/heroes/feta-haehnchen-blech.jpg",
  "frozen-coconut-strawberry-cups": "/brands/biene/heroes/frozen-coconut-strawberry-cups.jpg",
  "kaese-nudeln": "/brands/biene/heroes/kaese-nudeln.jpg",
  "kaese-zucchini-frittata": "/brands/biene/heroes/kaese-zucchini-frittata.jpg",
  "kartoffelsalat-protein-mayo": "/brands/biene/heroes/kartoffelsalat-protein-mayo.jpg",
  "ki-suesskartoffel-muffins": "/brands/biene/heroes/ki-suesskartoffel-muffins.jpg",
  "langos-airfryer-flammkuchen": "/brands/biene/heroes/langos-airfryer-flammkuchen.jpg",
  "lebensveraendernder-salat": "/brands/biene/heroes/lebensveraendernder-salat.jpg",
  "leichter-oster-zupfkuchen": "/brands/biene/heroes/leichter-oster-zupfkuchen.jpg",
  "marzipankartoffeln": "/brands/biene/heroes/marzipankartoffeln.jpg",
  "mealprep-lasagne": "/brands/biene/heroes/mealprep-lasagne.jpg",
  "mealprep-pizza-bowl": "/brands/biene/heroes/mealprep-pizza-bowl.jpg",
  "mini-franzbroetchen": "/brands/biene/heroes/mini-franzbroetchen.jpg",
  "protein-bananenbrot": "/brands/biene/heroes/protein-bananenbrot.jpg",
  "protein-griesspudding": "/brands/biene/heroes/protein-griesspudding.jpg",
  "protein-kaiserschmarren": "/brands/biene/heroes/protein-kaiserschmarren.jpg",
  "schoko-biskuitrolle": "/brands/biene/heroes/schoko-biskuitrolle.jpg",
  "spekulatius-tiramisu": "/brands/biene/heroes/spekulatius-tiramisu.jpg",
  "suesskartoffel-tarte": "/brands/biene/heroes/suesskartoffel-tarte.jpg",
  "viral-cloud-wrap": "/brands/biene/heroes/viral-cloud-wrap.jpg",
  "viral-xl-gemuese-wrap": "/brands/biene/heroes/viral-xl-gemuese-wrap.jpg",
  "virale-pasta-pfanne": "/brands/biene/heroes/virale-pasta-pfanne.jpg",
  "xl-mexican-bowl": "/brands/biene/heroes/xl-mexican-bowl.jpg",
  "xxl-frueh-cookie": "/brands/biene/heroes/xxl-frueh-cookie.jpg",
  "zimt-streuseltaler": "/brands/biene/heroes/zimt-streuseltaler.jpg",
  "zitronen-loeffelkuchen": "/brands/biene/heroes/zitronen-loeffelkuchen.jpg",
  "zuckerfreier-hefezopf": "/brands/biene/heroes/zuckerfreier-hefezopf.jpg",
};

// Helper that returns the hero URL for a recipe slug, or undefined if no
// image has been generated yet (custom recipes from the editor before the
// async enrichment kicks in).
export function getRecipeHero(slug: string): string | undefined {
  return recipeHeroes[slug];
}
