export type Ingredient = {
  amount: string;
  name: string;
  note?: string;
};

export type Micronutrient = {
  name: string;
  amount: string;
  pctDaily?: number;
};

export type Nutrition = {
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber?: number;
  sugar?: number;
  micros?: Micronutrient[];
};

export type Recipe = {
  slug: string;
  packSlug: string;
  number: number;
  title: string;
  subtitle: string;
  description: string;
  prepTime: number;
  cookTime?: number;
  difficulty: "Einfach" | "Mittel" | "Aufwendig";
  servings: number;
  tags: string[];
  ingredients: Ingredient[];
  steps: string[];
  nutrition: Nutrition;
  hero?: string;
  sourceUrl?: string;
  sourceLabel?: string;
};

export const recipes: Recipe[] = [
  // ─── Pack 1: Feierabend-Klassiker (7 Rezepte, original von @bienesfitlife) ───
  {
    slug: "kartoffelsalat-protein-mayo",
    packSlug: "feierabend-klassiker",
    number: 1,
    title: "Kartoffelsalat mit Protein-Mayo",
    subtitle: "5 große Portionen · 313 kcal · 1345 kcal gespart",
    description:
      "Bienes Klassiker für die Grillfeier — die cremige Mayo wird komplett aus hartgekochten Eiern gemixt. Niemand merkt, dass wir hier 1345 kcal sparen.",
    prepTime: 15,
    cookTime: 25,
    difficulty: "Einfach",
    servings: 5,
    tags: ["Anzeige", "High-Protein", "Grillklassiker", "Mealprep-tauglich"],
    ingredients: [
      { amount: "1000 g", name: "Kartoffeln" },
      { amount: "200 g", name: "Gewürzgurken" },
      { amount: "4", name: "Eier", note: "gekocht" },
      { amount: "Salz", name: "& Knobilicious-Gewürz" },
      { amount: "1 Bund", name: "Petersilie & Schnittlauch", note: "frisch" },
      { amount: "3", name: "Eier", note: "für die Mayo · hartgekocht" },
      { amount: "15 ml", name: "Öl", note: "für die Mayo · nach Wahl" },
      { amount: "50 ml", name: "Wasser", note: "für die Mayo" },
      { amount: "10 g", name: "Senf", note: "für die Mayo" },
      { amount: "1 Prise", name: "Salz", note: "für die Mayo" },
      { amount: "1 Spritzer", name: "Zitronensaft", note: "für die Mayo" },
      { amount: "20 g", name: "MORE Sahne Protein", note: "Geheimtipp · optional" },
    ],
    steps: [
      "Kartoffeln und Eier kochen. Kartoffeln pellen und abkühlen lassen, in der Zeit Gurken und Eier klein schneiden.",
      "Die Kartoffeln ebenfalls würfeln und alles in eine Schale geben.",
      "Für die Mayo alle Zutaten in einen Mixer geben — die Eier zuerst, dann alles cremig mixen. Optional 20 g MORE Sahne Protein für Extra-Cremigkeit & Sättigung.",
      "Mayo unter den Kartoffelsalat heben, mit Petersilie und Schnittlauch toppen, durchmischen und genießen!",
    ],
    nutrition: {
      kcal: 313,
      protein: 15,
      carbs: 34,
      fat: 12,
      fiber: 4,
    },
    sourceUrl: "https://www.instagram.com/reel/DW_GD7buV5s/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "kaese-nudeln",
    packSlug: "feierabend-klassiker",
    number: 2,
    title: "Käse-Nudeln zum Abnehmen",
    subtitle: "2 Portionen · 726 kcal · 51 g Protein · 15 Min",
    description:
      "Bienes virale Käse-Nudel-Pfanne — Schmelzkäse, MORE Trüffel-Mayo und Sahne Protein machen sie cremig wie Carbonara. Die perfekte große WPF-Mahlzeit für alle Käse-Nudel-Fans.",
    prepTime: 5,
    cookTime: 10,
    difficulty: "Einfach",
    servings: 2,
    tags: ["Anzeige", "High-Protein", "WPF-Mahlzeit", "Schnell"],
    ingredients: [
      { amount: "3 Scheiben", name: "Schmelzkäse" },
      { amount: "20 g", name: "Light Butter" },
      { amount: "1 EL", name: "Tomatenmark" },
      { amount: "1 EL", name: "MORE Light Gourmet Sauce", note: "z. B. Trüffel-Mayo" },
      { amount: "1 TL", name: "Gemüsebrühe-Gewürz" },
      { amount: "Gewürze", name: "z. B. MORE Pasta Allrounder" },
      { amount: "500 ml", name: "Mandelmilch ungesüßt" },
      { amount: "180 g", name: "Mie-Nudeln" },
      { amount: "etwas", name: "Salz" },
      { amount: "70 g", name: "MORE Sahne Protein" },
      { amount: "100 ml", name: "Mandelmilch", note: "für die Protein-Sahne" },
      { amount: "Petersilie", name: "frisch" },
      { amount: "2 Scheiben", name: "Schmelzkäse", note: "Topping · 1 pro Schüssel" },
    ],
    steps: [
      "3 Scheiben Schmelzkäse mit Butter, Tomatenmark, Mayo und Gewürzen in einer Pfanne bei mittlerer Hitze schmelzen.",
      "Mit 500 ml Mandelmilch ablöschen, gut verrühren, dann die Mie-Nudeln hineingeben. Mit Deckel 10 Minuten köcheln lassen, ggf. einmal wenden.",
      "In der Kochzeit Sahne Protein mit 100 ml Mandelmilch anrühren. Nudeln in der Pfanne vermengen, Hitze aus, Protein-Sahne unterziehen.",
      "Auf zwei Schüsseln verteilen, mit je einer Scheibe Schmelzkäse toppen und Petersilie servieren.",
    ],
    nutrition: {
      kcal: 726,
      protein: 51,
      carbs: 75,
      fat: 24,
      fiber: 4,
    },
    sourceUrl: "https://www.instagram.com/reel/DV9J1iBDuIJ/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "blech-pasta",
    packSlug: "feierabend-klassiker",
    number: 3,
    title: "Blech-Pasta",
    subtitle: "2 Portionen · 692 kcal · 53 g Protein",
    description:
      "Spaghetti, Salakis Feta und Cocktail-Tomaten aufs Blech — der Ofen macht den Rest. In 5 Minuten vorbereitet, perfekt als Mealprep.",
    prepTime: 5,
    cookTime: 25,
    difficulty: "Einfach",
    servings: 2,
    tags: ["Anzeige", "High-Protein", "WPF-Mahlzeit", "Mealprep"],
    ingredients: [
      { amount: "200 g", name: "Spaghetti", note: "ungekocht gewogen" },
      { amount: "180 g", name: "Salakis Feta Light" },
      { amount: "400 g", name: "Cocktail-Tomaten" },
      { amount: "1", name: "Zwiebel", note: "klein, gehackt" },
      { amount: "600–800 ml", name: "Gemüsebrühe" },
      { amount: "40 g", name: "Tomatenmark" },
      { amount: "Gewürze", name: "z. B. MORE Italian Allrounder" },
      { amount: "50 g", name: "MORE Sahne Protein" },
      { amount: "100 ml", name: "Mandelmilch", note: "für die Protein-Sahne" },
    ],
    steps: [
      "Backofen auf 180 °C Ober-/Unterhitze vorheizen.",
      "Gemüsebrühe zum Kochen bringen und Tomatenmark einrühren.",
      "Spaghetti aufs Blech verteilen, mit Feta, halbierten Cocktail-Tomaten und gehackter Zwiebel toppen, mit der Brühe übergießen und ca. 25 Min bei 180 °C backen.",
      "In der Zeit Sahne Protein mit Mandelmilch anrühren. Nach dem Backen mit der Protein-Sauce und Gewürzen vermengen.",
    ],
    nutrition: {
      kcal: 692,
      protein: 53,
      carbs: 92,
      fat: 12,
      fiber: 6,
    },
    sourceUrl: "https://www.instagram.com/reel/DVTnnPEDJPz/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "virale-pasta-pfanne",
    packSlug: "feierabend-klassiker",
    number: 4,
    title: "Virale Pasta-Pfanne",
    subtitle: "2 Portionen · 750 kcal · 54 g Protein",
    description:
      "Tomaten, Zwiebeln und Veggie-Hack zu Pasta-Sauce gedünstet — mit Käse, Nudeln und MORE Sahne Protein zur perfekten großen WPF-Mahlzeit.",
    prepTime: 10,
    cookTime: 20,
    difficulty: "Einfach",
    servings: 2,
    tags: ["Anzeige", "High-Protein", "WPF-Mahlzeit", "Sattmacher"],
    ingredients: [
      { amount: "5–6", name: "große Tomaten" },
      { amount: "etwas", name: "Ölspray" },
      { amount: "1", name: "Zwiebel", note: "gehackt" },
      { amount: "250 g", name: "Veggie-Hack", note: "oder normales Hack" },
      { amount: "1 Schuss", name: "Wasser" },
      { amount: "1 EL", name: "Tomatenmark" },
      { amount: "Gewürze", name: "z. B. MORE Pasta Allrounder" },
      { amount: "100 g", name: "geriebener Käse Light" },
      { amount: "180 g", name: "Nudeln", note: "ungekocht gewogen" },
      { amount: "20 g", name: "MORE Sahne Protein" },
      { amount: "50–80 ml", name: "Mandelmilch", note: "für die Protein-Sahne" },
      { amount: "Basilikum", name: "frisch" },
    ],
    steps: [
      "Tomaten in etwas Ölspray mit Wasser und gehackten Zwiebeln bei mittlerer Hitze mit Deckel ca. 10 Min dünsten.",
      "Hack zugeben und anbraten. Bei den Tomaten die Haut abziehen und sie kleindrücken.",
      "Mit Tomatenmark abschmecken, würzen, Käse einrühren.",
      "Mit gekochten Nudeln vermengen und mit Sahne Protein und etwas Käse toppen. Hitze aus, kurz ziehen lassen — fertig!",
    ],
    nutrition: {
      kcal: 750,
      protein: 54,
      carbs: 87,
      fat: 23,
      fiber: 7,
    },
    sourceUrl: "https://www.instagram.com/reel/DU_csfmDmzO/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "viral-cloud-wrap",
    packSlug: "feierabend-klassiker",
    number: 5,
    title: "Viral Cloud Wrap",
    subtitle: "1 XL-Wrap · 235 kcal Basis · 28 g Protein",
    description:
      "Eiklar-Wrap aus dem Ofen — XL-Mahlzeit, super sättigend und nur knapp 200 kcal als Basis. Perfekt für Volumen-Lover, die abnehmen wollen.",
    prepTime: 5,
    cookTime: 10,
    difficulty: "Einfach",
    servings: 1,
    tags: ["XL-Mahlzeit", "Volumen", "Low-Carb", "High-Protein"],
    ingredients: [
      { amount: "225 ml", name: "Eiklar" },
      { amount: "10 g", name: "Speisestärke" },
      { amount: "Salz", name: "" },
      { amount: "Gewürze", name: "z. B. MORE Knobilicious" },
      { amount: "50 g", name: "Exquisa fitline", note: "Belag" },
      { amount: "Eisbergsalat", name: "nach Wahl · Belag" },
      { amount: "1", name: "Spiegelei", note: "Belag" },
      { amount: "1", name: "große Tomate", note: "Belag" },
      { amount: "35 g", name: "Light Gouda", note: "Belag" },
      { amount: "MORE Light Gourmet Sauce", name: "Honey Mustard + Trüffel-Mayo · Belag" },
    ],
    steps: [
      "Backofen auf 180 °C Umluft vorheizen.",
      "Eiklar sehr steif schlagen, dann Speisestärke und Gewürze einrieseln lassen und vorsichtig unterheben.",
      "Auf einem Backpapier auf Backblechgröße verstreichen und 8–10 Min bei 180 °C backen, bis es leicht goldbraun, aber noch nicht knusprig fest ist.",
      "Vom Backpapier vorsichtig lösen, mit Frischkäse, Gouda, Tomate, Spiegelei, Salat und Saucen belegen — fertig!",
    ],
    nutrition: {
      kcal: 235,
      protein: 28,
      carbs: 11,
      fat: 8,
    },
    sourceUrl: "https://www.instagram.com/reel/DUqnNhMjIKL/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "blitz-cheeseburger-auflauf",
    packSlug: "feierabend-klassiker",
    number: 6,
    title: "Blitz Cheeseburger-Auflauf",
    subtitle: "2 Portionen · 683 kcal · 53 g Protein",
    description:
      "Kartoffeln, Veggie-Hack und Burger-Sauce mit Schmelzkäse überbacken — schmeckt nach purer Sünde, ist aber Abnehm-Mealprep für 2 Tage.",
    prepTime: 10,
    cookTime: 15,
    difficulty: "Einfach",
    servings: 2,
    tags: ["Anzeige", "High-Protein", "Sattmacher", "Mealprep"],
    ingredients: [
      { amount: "600 g", name: "Kartoffeln", note: "roh gewogen" },
      { amount: "250 g", name: "Veggie-Hack", note: "z. B. Rügenwalder · oder leichtes Hack" },
      { amount: "4 Scheiben", name: "Schmelzkäse" },
      { amount: "50 g", name: "Gewürzgurken" },
      { amount: "80 ml", name: "Mandelmilch", note: "für die Burger-Sauce" },
      { amount: "50 ml", name: "passierte Tomaten", note: "für die Burger-Sauce" },
      { amount: "etwas", name: "Light-Ketchup", note: "optional · für die Sauce" },
      { amount: "60 g", name: "MORE Sahne Protein", note: "für die Burger-Sauce" },
      { amount: "Salz", name: "& MORE Italian Allrounder" },
      { amount: "1 EL", name: "MORE Light Gourmet Sauce", note: "Burger Sauce · optional" },
    ],
    steps: [
      "Gekochte Kartoffeln pellen, vierteln und in eine Auflaufform geben.",
      "Hack mit etwas Ölspray anbraten und auf den Kartoffeln verteilen.",
      "Sauce separat anrühren (Mandelmilch, Tomaten, optional Ketchup, Sahne Protein, Gewürze), abschmecken und auf dem Hack verstreichen.",
      "Mit Schmelzkäse und Gewürzgurken toppen, bei 175 °C Umluft ca. 15 Min überbacken — fertig!",
    ],
    nutrition: {
      kcal: 683,
      protein: 53,
      carbs: 69,
      fat: 25,
      fiber: 8,
    },
    sourceUrl: "https://www.instagram.com/reel/DUoK7j1jtnd/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "langos-airfryer-flammkuchen",
    packSlug: "feierabend-klassiker",
    number: 7,
    title: "Langos im Airfryer · Flammkuchen-Style",
    subtitle: "1 Langos · 442 kcal · 37 g Protein · 10 Min",
    description:
      "Knuspriger Dinkel-Magerquark-Teig mit cremigem Frischkäse, Schinken-Würfeln und Frühlingszwiebeln — die perfekte kleine WPF-Mahlzeit aus dem Airfryer.",
    prepTime: 5,
    cookTime: 15,
    difficulty: "Einfach",
    servings: 1,
    tags: ["High-Protein", "WPF-Mahlzeit", "Airfryer"],
    ingredients: [
      { amount: "70 g", name: "Dinkelmehl", note: "Teig" },
      { amount: "30 g", name: "MORE Sahne Protein", note: "Teig" },
      { amount: "4 g", name: "Backpulver", note: "Teig" },
      { amount: "etwas", name: "Salz", note: "Teig" },
      { amount: "50 g", name: "Magerquark", note: "Teig" },
      { amount: "ca. 40 ml", name: "Wasser", note: "Teig" },
      { amount: "2 Sprüher", name: "Ölspray", note: "Teig" },
      { amount: "40 g", name: "Exquisa fitline", note: "Topping" },
      { amount: "Gewürze", name: "z. B. MORE Knobilicious · Topping" },
      { amount: "15–20 g", name: "Schinken-Würfel", note: "Topping · z. B. Veggie von Billie Green" },
      { amount: "1/4", name: "rote Zwiebel", note: "Topping" },
      { amount: "Frühlingszwiebeln", name: "Topping" },
    ],
    steps: [
      "Alle trockenen Zutaten für den Teig vermengen, dann mit Magerquark und Wasser verkneten und zu einem Fladen formen.",
      "Frischkäse mit etwas Wasser cremig rühren und den Fladen damit toppen.",
      "Mit roten Zwiebeln und Schinken-Würfeln abschließen und 15 Min bei ca. 130 °C in den Airfryer geben.",
      "Mit Frühlingszwiebeln abschließen und noch warm genießen!",
    ],
    nutrition: {
      kcal: 442,
      protein: 37,
      carbs: 60,
      fat: 6,
      fiber: 6,
    },
    sourceUrl: "https://www.instagram.com/reel/DUfO5PCDImH/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },

  // ─── Pack 2: Bienes Backwelt (10 Rezepte, original von @bienesfitlife) ───
  {
    slug: "schoko-biskuitrolle",
    packSlug: "bienes-backwelt",
    number: 1,
    title: "High Protein Schoko-Biskuitrolle",
    subtitle: "10 Stücke · 172 kcal · 14 g Protein",
    description:
      "Bienes legendäre Schoko-Biskuitrolle mit cremiger Vanille-Schlagcreme — fast zuckerfrei, mit insgesamt 140 g Protein in der ganzen Rolle. 2,5 Stücke = kleine WPF-Mahlzeit mit 35 g Protein.",
    prepTime: 25,
    cookTime: 15,
    difficulty: "Mittel",
    servings: 10,
    tags: ["Anzeige", "High-Protein", "ohne Zucker", "Klassiker"],
    ingredients: [
      { amount: "50 g", name: "Mehl", note: "Teig" },
      { amount: "20 g", name: "MORE Protein Sahne", note: "Teig · oder Iced Coffee oder mehr Mehl" },
      { amount: "20 g", name: "Backkakao", note: "Teig" },
      { amount: "1 TL", name: "Backpulver", note: "Teig" },
      { amount: "1/4 TL", name: "Salz", note: "Teig" },
      { amount: "4", name: "Eier", note: "Teig · getrennt" },
      { amount: "140 g", name: "No More Sugar", note: "Teig · oder Erythrit" },
      { amount: "50 g", name: "Butter", note: "Teig · geschmolzen" },
      { amount: "100 g", name: "MORE Protein Schlagcreme", note: "Creme · oder 200 ml Cremefine 19 %" },
      { amount: "300 ml", name: "Mandelmilch", note: "Creme · für die Schlagcreme" },
      { amount: "9 g", name: "MORE Chunky Flavour", note: "Creme · z. B. Vanilla Perfection" },
      { amount: "1–2 Pck", name: "Sahne steif", note: "Creme" },
      { amount: "200 g", name: "Exquisa fitline 2 %", note: "Creme" },
      { amount: "40 g", name: "dunkle 85 % Schokolade", note: "Topping · optional zum Übergießen" },
    ],
    steps: [
      "Ofen auf 170 °C O/U (150 °C Umluft) vorheizen, Blech (37 × 24 cm) mit Backpapier auslegen.",
      "Trockene Zutaten mischen: Mehl, Kakao, Protein, Backpulver, Salz.",
      "Eiweiß steif schlagen, dabei nach und nach die Hälfte des Erythrits einrieseln lassen.",
      "Eigelb mit dem restlichen Erythrit 5 Min cremig schlagen.",
      "Eischnee vorsichtig unterheben, trockene Zutaten einsieben, zum Schluss die geschmolzene Butter einarbeiten.",
      "Teig aufs Blech, glatt streichen, ca. 10–20 Min backen.",
      "Direkt mit Kakao bestäuben, Backpapier drauf, umdrehen, unteres Backpapier abziehen und mit Papier einrollen. Auskühlen lassen.",
      "Für die Creme alle Zutaten zusammen steif schlagen.",
      "Rolle entrollen, Creme verstreichen, wieder einrollen. Mind. 1 Stunde kühlen. Optional mit dunkler Schokolade übergießen.",
    ],
    nutrition: {
      kcal: 172,
      protein: 14,
      carbs: 8,
      fat: 9,
    },
    sourceUrl: "https://www.instagram.com/reel/DXwIRHpMmaU/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "erdbeer-biscuit-pudding-kuchen",
    packSlug: "bienes-backwelt",
    number: 2,
    title: "Erdbeer-Biscuit-Kuchen mit Vanille Pudding",
    subtitle: "8 Stücke · 117 kcal · 8 g Protein",
    description:
      "Bienes legendärer Erdbeer-Kuchen mit fluffigem Biskuit, Vanille-Pudding-Schicht und frischen Erdbeeren — ohne Zucker und niemand merkt's. Achtung: kein Backpulver im Teig!",
    prepTime: 25,
    cookTime: 20,
    difficulty: "Mittel",
    servings: 8,
    tags: ["Anzeige", "ohne Zucker", "High-Protein", "Sommer"],
    ingredients: [
      { amount: "4", name: "Eier", note: "Teig" },
      { amount: "75 g", name: "no more Sugar", note: "Teig" },
      { amount: "30 g", name: "Mehl", note: "Teig" },
      { amount: "20 g", name: "MORE Protein Sahne", note: "Teig · oder mehr Mehl" },
      { amount: "6 g", name: "MORE Chunky Vanilla Perfection", note: "Teig · optional" },
      { amount: "20 g", name: "Puddingpulver Vanille", note: "Teig" },
      { amount: "1 Msp", name: "Salz", note: "Teig · KEIN Backpulver!" },
      { amount: "1 Pck", name: "Puddingpulver Vanille", note: "Creme" },
      { amount: "200 ml", name: "Mandelmilch ungesüßt", note: "Creme" },
      { amount: "150 g", name: "Magerquark", note: "Creme" },
      { amount: "3 g", name: "MORE Chunky Vanilla Perfection", note: "Creme" },
      { amount: "400 g", name: "frische Erdbeeren", note: "Topping" },
      { amount: "1 Pck", name: "Tortenguss rot", note: "Topping" },
      { amount: "1 Prise", name: "MORE Chunky Vanilla", note: "Topping · oder 2 EL Erythrit" },
    ],
    steps: [
      "Backofen auf 160 °C Umluft (180 °C O/U) vorheizen.",
      "Eier mit no more Sugar 4 Min aufschlagen, bis eine fest-fluffige Masse entsteht (es muss wirklich fest sein).",
      "Restliche trockene Zutaten vermengen, in die Eimasse sieben und unterheben.",
      "Teig in die 26er Form füllen, ca. 15–20 Min backen (nach 10 Min mit Alufolie abdecken).",
      "Für die Creme Puddingpulver mit kalter Mandelmilch in einem Topf verrühren und unter Rühren aufkochen.",
      "Magerquark schnell unterrühren, mit Chunky süßen, auf den abgekühlten Biskuitboden verstreichen.",
      "Mit halbierten Erdbeeren belegen.",
      "Tortenguss nach Packungsanleitung mit Chunky/Erythrit statt Zucker zubereiten und über die Erdbeeren geben.",
      "Mindestens 1 Stunde kalt stellen und genießen!",
    ],
    nutrition: {
      kcal: 117,
      protein: 8,
      carbs: 14,
      fat: 3,
    },
    sourceUrl: "https://www.instagram.com/reel/DXtgtyyDAiI/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "blaubeer-cheesecake-no-bake",
    packSlug: "bienes-backwelt",
    number: 3,
    title: "Blaubeer-Cheesecake ohne Backen",
    subtitle: "10 Stücke · 149 kcal · 18 g Protein",
    description:
      "Bienes cremigster No-Bake-Cheesecake — mit Blueberry-Lavender-Note, ohne Zuckerzusatz. 2 Stücke = kleine WPF-Mahlzeit mit 36 g Protein.",
    prepTime: 30,
    cookTime: 0,
    difficulty: "Mittel",
    servings: 10,
    tags: ["Anzeige", "No-Bake", "ohne Zucker", "High-Protein", "WPF-Mahlzeit"],
    ingredients: [
      { amount: "60 g", name: "zuckerreduzierte Butterkekse", note: "Boden" },
      { amount: "60 g", name: "zarte Haferflocken", note: "Boden" },
      { amount: "40 g", name: "MORE Protein Sahne", note: "Boden" },
      { amount: "3 g", name: "MORE Chunky Vanilla Perfection", note: "Boden" },
      { amount: "100 g", name: "Exquisa Fitline 0,2 %", note: "Boden" },
      { amount: "500 g", name: "Magerquark", note: "Creme" },
      { amount: "200 g", name: "Exquisa Fitline 0,2 %", note: "Creme" },
      { amount: "40 g", name: "MORE Protein Schlagcreme", note: "Creme" },
      { amount: "200 ml", name: "Mandelmilch", note: "Creme" },
      { amount: "6 Blatt", name: "Gelatine", note: "Creme" },
      { amount: "9 g", name: "MORE Chunky Flavour", note: "Creme · z. B. Blueberry Lavender" },
      { amount: "150 g", name: "Blaubeeren TK", note: "Topping" },
      { amount: "5 g", name: "Speisestärke", note: "Topping" },
    ],
    steps: [
      "Boden: Kekse und Haferflocken im Mixer zerkleinern. Mit Frischkäse, Protein Sahne und Chunky verkneten. In der 18er Form fest andrücken.",
      "Creme: Magerquark, Frischkäse und Chunky verrühren.",
      "6 Blatt Gelatine 5 Min in kaltem Wasser einweichen, ausdrücken und im Topf erwärmen bis geschmolzen (NICHT kochen).",
      "Zunächst 2 EL der Quark-Creme in die Gelatine rühren (Temperaturangleich), dann fix mit dem restlichen Quark vermixen.",
      "Schlagcreme mit Mandelmilch aufschlagen und unterheben (2 EL für Tupfer aufheben). Creme auf den Boden geben.",
      "Optional: TK-Blaubeeren erwärmen und 3 EL in der obersten Kuchenschicht verswirlen.",
      "Mind. 2 Stunden in den Kühlschrank.",
      "Restliche Blaubeeren aufkochen, mit 20 ml kaltem Wasser angerührter Speisestärke einrühren. Auf den Kuchen geben.",
      "Mit restlicher Schlagcreme Tupfer machen — fertig!",
    ],
    nutrition: {
      kcal: 149,
      protein: 18,
      carbs: 15,
      fat: 2,
    },
    sourceUrl: "https://www.instagram.com/reel/DXOhpecOZAw/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "erdbeer-kuppeltorte",
    packSlug: "bienes-backwelt",
    number: 4,
    title: "Erdbeer-Kuppeltorte",
    subtitle: "8 Stücke · 149 kcal · 18 g Protein",
    description:
      "Bienes Angeber-Kuppeltorte mit Erdbeer-Quark-Creme zwischen Biskuit-Schichten — ohne Zuckerzusatz, mit pürierten und ganzen Erdbeeren.",
    prepTime: 35,
    cookTime: 20,
    difficulty: "Aufwendig",
    servings: 8,
    tags: ["Anzeige", "ohne Zucker", "High-Protein", "Show-Off"],
    ingredients: [
      { amount: "3", name: "Eier", note: "Teig" },
      { amount: "75 g", name: "Erythrit", note: "Teig" },
      { amount: "30 g", name: "Weizenmehl", note: "Teig" },
      { amount: "20 g", name: "MORE Protein Sahne", note: "Teig" },
      { amount: "20 g", name: "Puddingpulver Vanille", note: "Teig" },
      { amount: "500 g", name: "Magerquark", note: "Creme" },
      { amount: "50 g", name: "MORE Protein Schlagcreme", note: "Creme" },
      { amount: "200 ml", name: "Mandelmilch", note: "Creme · für die Schlagcreme" },
      { amount: "7 Blatt", name: "Gelatine", note: "Creme" },
      { amount: "5 g", name: "MORE Chunky Strawberry/Vanilla", note: "Creme" },
      { amount: "150 g", name: "Erdbeeren", note: "Creme · püriert" },
      { amount: "300 g", name: "frische Erdbeeren", note: "Topping" },
    ],
    steps: [
      "Backofen auf 180 °C O/U vorheizen. Eier mit Erythrit 4 Min auf höchster Stufe schlagen, bis eine 3-fache fest-fluffige Masse entsteht.",
      "Trockene Zutaten vermengen, in die Eimasse sieben und unterheben.",
      "In die 18er Springform füllen, 15–20 Min backen (nach 10 Min mit Alufolie abdecken). Etwas abkühlen lassen, in zwei Hälften schneiden.",
      "Für die Creme: Erdbeeren pürieren, Schlagcreme aufschlagen, alles mit Magerquark und Chunky verrühren.",
      "Gelatineblätter einweichen, ausdrücken, im Topf erwärmen (nicht kochen). Mit 4 EL Quark-Creme anrühren, dann unter die gesamte Masse rühren.",
      "Erdbeeren für das Topping in dünne Scheiben schneiden.",
      "Eine Schale fetten und mit Frischhaltefolie auskleiden, mit Erdbeer-Scheiben auskleiden.",
      "Creme und Biskuit-Böden abwechselnd schichten.",
      "Mindestens 2–3 Stunden kalt stellen und genießen!",
    ],
    nutrition: {
      kcal: 149,
      protein: 18,
      carbs: 12,
      fat: 3,
    },
    sourceUrl: "https://www.instagram.com/reel/DXJ8XAus1oj/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "protein-bananenbrot",
    packSlug: "bienes-backwelt",
    number: 5,
    title: "Protein-Bananenbrot",
    subtitle: "10 Scheiben · 145 kcal · 10 g Protein",
    description:
      "Bienes Bananenbrot mit Schoki-Swirl und dunkler Schokolade — ohne zugesetzten Zucker, super saftig. 3 Scheiben = kleine WPF-Mahlzeit mit 30 g Protein.",
    prepTime: 10,
    cookTime: 50,
    difficulty: "Einfach",
    servings: 10,
    tags: ["Anzeige", "ohne Zucker", "High-Protein", "WPF-Mahlzeit"],
    ingredients: [
      { amount: "2", name: "Bananen", note: "Teig · zerdrückt" },
      { amount: "2", name: "Eier", note: "Teig" },
      { amount: "120 g", name: "Magerquark", note: "Teig" },
      { amount: "120 g", name: "Dinkelmehl", note: "Teig" },
      { amount: "70 g", name: "MORE Protein Sahne", note: "Teig" },
      { amount: "100 g", name: "Erythrit", note: "Teig · oder no more Sugar" },
      { amount: "10 g", name: "Backpulver", note: "Teig" },
      { amount: "3 g", name: "MORE Chunky Vanilla Perfection", note: "Teig" },
      { amount: "5 g", name: "Backkakao", note: "Teig · für 1/3 Schoki-Schicht" },
      { amount: "5 g", name: "MORE Chunky Ultra Dark Choc", note: "Teig · für 1/3 Schoki-Schicht" },
      { amount: "40 g", name: "dunkle 80 % Schokolade", note: "Topping · gehackt" },
      { amount: "1", name: "Banane", note: "Topping · längs halbiert" },
    ],
    steps: [
      "Backofen auf 180 °C Umluft vorheizen. Bananen mit Gabel zerdrücken, Eier und Magerquark unterrühren.",
      "Alle trockenen Zutaten für den hellen Teig dazugeben und verrühren.",
      "1/3 des Teigs in eine andere Schüssel füllen und mit Backkakao und schokoladigem Chunky verrühren.",
      "Hellen Teig in die Frame-M-Form füllen, mit Schoki-Teig toppen.",
      "2/3 der gehackten Schokolade drüber, 2× alles mit einer Gabel durchswirlen.",
      "Mit der halbierten Banane und restlichen Schoko-Stücken toppen.",
      "30 Min bei 180 °C backen, mit Alufolie abdecken und weitere 15–20 Min backen.",
    ],
    nutrition: {
      kcal: 145,
      protein: 10,
      carbs: 17,
      fat: 4,
    },
    sourceUrl: "https://www.instagram.com/reel/DXFPSjmurtI/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "ki-suesskartoffel-muffins",
    packSlug: "bienes-backwelt",
    number: 6,
    title: "Virale KI-Süßkartoffel-Muffins",
    subtitle: "9 Stück · 82 kcal · 8 g Protein",
    description:
      "Bienes virale Süßkartoffel-Muffins — nur 80 kcal pro Stück, ohne Zucker, mit hohem Proteingehalt. 4 Stück = kleine WPF-Mahlzeit mit 31 g Protein.",
    prepTime: 10,
    cookTime: 25,
    difficulty: "Einfach",
    servings: 9,
    tags: ["Anzeige", "ohne Zucker", "High-Protein", "Snack", "Schnell"],
    ingredients: [
      { amount: "200 g", name: "Süßkartoffel", note: "gekocht" },
      { amount: "70 g", name: "Mehl" },
      { amount: "70 g", name: "MORE Protein Sahne" },
      { amount: "50 g", name: "Erythrit" },
      { amount: "1 Spritzer", name: "MORE Zerup Barista", note: "z. B. Brown Sugar" },
      { amount: "8 g", name: "Backpulver" },
      { amount: "50 g", name: "Magerquark" },
      { amount: "40 ml", name: "Mandelmilch" },
    ],
    steps: [
      "Süßkartoffel kochen, Schale abziehen. Backofen auf 180 °C Umluft vorheizen.",
      "Süßkartoffel kleindrücken und mit allen restlichen Zutaten zu einem Teig vermengen.",
      "Auf 9 Muffin-Förmchen aufteilen, 20–25 Min backen.",
      "Stäbchenprobe: wenn nichts mehr klebt, sind sie fertig!",
    ],
    nutrition: {
      kcal: 82,
      protein: 8,
      carbs: 12,
      fat: 1,
    },
    sourceUrl: "https://www.instagram.com/reel/DW6BsuisKXc/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "leichter-oster-zupfkuchen",
    packSlug: "bienes-backwelt",
    number: 7,
    title: "Leichter Oster-Zupfkuchen",
    subtitle: "16 Stücke · 174 kcal · 14 g Protein · 4,6 g Zucker",
    description:
      "Bienes Hommage an den Dr.-Oetker-Klassiker — kalorienarm abgewandelt, mit 3395 kcal gespart gegenüber dem Original (das hat 22 g Zucker pro Stück, dieser nur 4,6 g).",
    prepTime: 30,
    cookTime: 50,
    difficulty: "Aufwendig",
    servings: 16,
    tags: ["Anzeige", "ohne Zucker", "Klassiker", "Show-Off"],
    ingredients: [
      { amount: "175 g", name: "Dinkelmehl Type 630", note: "Boden" },
      { amount: "75 g", name: "MORE Sahne Protein", note: "Boden" },
      { amount: "100 g", name: "no more Sugar", note: "Boden" },
      { amount: "25 g", name: "Backkakao", note: "Boden" },
      { amount: "5 g", name: "Backpulver", note: "Boden" },
      { amount: "6 g", name: "MORE Chunky Ultra Dark Choc", note: "Boden" },
      { amount: "1", name: "Ei", note: "Boden" },
      { amount: "60 g", name: "Butter", note: "Boden · flüssig" },
      { amount: "80 g", name: "Magerquark", note: "Boden" },
      { amount: "250 g", name: "Aprikosenhälften", note: "Boden · ungezuckert" },
      { amount: "500 g", name: "Magerquark", note: "Creme" },
      { amount: "400 g", name: "Exquisa fitline", note: "Creme" },
      { amount: "100 ml", name: "Cremefine 19 %", note: "Creme · separat steif schlagen" },
      { amount: "2", name: "Eier", note: "Creme" },
      { amount: "6 g", name: "MORE Chunky Vanilla", note: "Creme" },
      { amount: "1 Pck", name: "Vanille-Puddingpulver", note: "Creme" },
    ],
    steps: [
      "Trockene Zutaten für den Schoko-Teig vermengen. Flüssige Butter, Magerquark und Ei dazugeben, zu einem Teig kneten.",
      "1/3 des Teigs mit etwas Mehl dünn ausrollen, mit Keks-Ausstechern Motive ausstechen (ca. 14 Stück), beiseite legen.",
      "Restlichen Teig wieder zusammenkneten, ausrollen und damit den Boden der Frame-L-Form bedecken.",
      "Für die Creme: Sahne separat steif schlagen. Restliche Zutaten vermixen. Sahne vorsichtig unterheben.",
      "Aprikosen auf dem Schoki-Teig verteilen.",
      "Quark-Creme vorsichtig drüber geben und mit den Motiv-Teigstücken dekorieren.",
      "Bei 170 °C O/U ca. 45–55 Min backen.",
      "Im Ofen vollständig abkühlen lassen, am besten über Nacht in den Kühlschrank.",
    ],
    nutrition: {
      kcal: 174,
      protein: 14,
      carbs: 15,
      fat: 6,
      sugar: 4.6,
    },
    sourceUrl: "https://www.instagram.com/reel/DWrKSEPMO_G/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "mini-franzbroetchen",
    packSlug: "bienes-backwelt",
    number: 8,
    title: "Mini Franzbrötchen",
    subtitle: "12 Stück · 118 kcal · 9 g Eiweiß · 15 Min",
    description:
      "Bienes Mini-Franzbrötchen ohne Hefe — in 15 Min im Ofen, ohne Zuckerzusatz. Saftig und perfekt für die ganze Familie. Schmecken am besten noch warm.",
    prepTime: 15,
    cookTime: 11,
    difficulty: "Einfach",
    servings: 12,
    tags: ["Anzeige", "ohne Zucker", "ohne Hefe", "Schnell"],
    ingredients: [
      { amount: "180 g", name: "Dinkelmehl Type 630", note: "Teig" },
      { amount: "80 g", name: "MORE Protein Sahne", note: "Teig" },
      { amount: "6 g", name: "MORE Chunky Vanilla Perfection", note: "Teig" },
      { amount: "11 g", name: "Backpulver", note: "Teig" },
      { amount: "150 g", name: "Magerquark", note: "Teig" },
      { amount: "1", name: "Ei", note: "Teig · M" },
      { amount: "30 g", name: "Light-Butter", note: "Teig · z. B. Meggle Joghurt-Butter" },
      { amount: "MORE ZimtkeinZucker", name: "nach Belieben", note: "Füllung · oder Erythrit + Zimt" },
      { amount: "20 g", name: "Light-Butter", note: "Füllung" },
    ],
    steps: [
      "Backofen auf 180 °C Umluft vorheizen. Trockene Zutaten für den Teig vermengen.",
      "Geschmolzene Butter, Ei und Magerquark dazugeben, zu einem Teig verkneten.",
      "Teig in zwei Hälften teilen. Jeweils auf bemehlter Fläche rechteckig auf ca. die Größe eines halben Backbleches ausrollen.",
      "Dünn mit geschmolzener Butter bestreichen, kräftig mit ZimtkeinZucker bestreuen.",
      "Jeweils zu einer Teigrolle aufrollen und in 3–4 cm lange Stücke trennen.",
      "Auf einer Backfolie drapieren und mit einem Kochlöffel in der Mitte tief hinunterdrücken (typische Franzbrötchen-Form).",
      "Vor dem Backen nochmal mit der restlichen Butter bestreichen und mit ZimtkeinZucker bestreuen.",
      "11 Min bei 180 °C Umluft goldbraun backen.",
    ],
    nutrition: {
      kcal: 118,
      protein: 9,
      carbs: 12,
      fat: 4,
    },
    sourceUrl: "https://www.instagram.com/reel/DWgWv8_snyi/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "zuckerfreier-hefezopf",
    packSlug: "bienes-backwelt",
    number: 9,
    title: "Zuckerfreier Hefezopf",
    subtitle: "14 Scheiben · 137 kcal · 4 g Protein",
    description:
      "Bienes klassischer Hefezopf — fast komplett zuckerfrei (nur 1 EL für die Hefe). Optionale Protein-Variante: 350 g Mehl + 50 g MORE Sahne Protein → 6 g Protein pro Scheibe.",
    prepTime: 30,
    cookTime: 25,
    difficulty: "Mittel",
    servings: 14,
    tags: ["Anzeige", "ohne Zucker", "Klassiker", "Hefeteig"],
    ingredients: [
      { amount: "400 g", name: "Mehl", note: "oder 350 g Mehl + 50 g MORE Protein Sahne für Protein-Variante" },
      { amount: "150 ml", name: "Mandelmilch", note: "warm aus Topf/Mikrowelle" },
      { amount: "1/2 Würfel", name: "frische Hefe" },
      { amount: "1 EL", name: "Zucker", note: "einziger Zucker im Rezept!" },
      { amount: "75 g", name: "no more Sugar", note: "oder Erythrit" },
      { amount: "2", name: "Eier" },
      { amount: "50 g", name: "Butter", note: "warm" },
      { amount: "9 g", name: "MORE Chunky Vanilla Perfection", note: "oder Morezipan" },
      { amount: "1 Prise", name: "Salz" },
      { amount: "1", name: "Eigelb", note: "Topping" },
      { amount: "1 Schuss", name: "Milch", note: "Topping · für die Eigelb-Glasur" },
      { amount: "Hagelzucker", name: "oder gehobelte Mandeln", note: "Topping" },
    ],
    steps: [
      "Mehl in eine Schüssel geben. Milch leicht erwärmen und in eine Mulde im Mehl kippen.",
      "Hefe in die warme Milch bröseln, EL Zucker dazu, in der Milch verrühren bis Hefe aufgelöst ist. 10 Min abgedeckt stehen lassen.",
      "Eier, Erythrit, Chunky und Butter dazugeben und alles mit Maschine/Mixer verkneten bis ein klebriger Teig entsteht.",
      "Teig auf bemehlter Fläche etwas falten, in bemehlter Schüssel an warmen Ort zugedeckt 45 Min gehen lassen.",
      "Teig in 3 Stränge teilen und von der Mitte her flechten (Achtung: Protein-Teig ist klebrig).",
      "Auf Blech nochmal 15–20 Min zugedeckt gehen lassen.",
      "Mit Eigelb-Milch-Mischung bestreichen, dekorieren, bei 180 °C O/U 20–30 Min backen.",
    ],
    nutrition: {
      kcal: 137,
      protein: 4,
      carbs: 22,
      fat: 4,
    },
    sourceUrl: "https://www.instagram.com/reel/DWUY7L8O24k/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "einfachstes-protein-brot",
    packSlug: "bienes-backwelt",
    number: 10,
    title: "Einfachstes Protein-Brot",
    subtitle: "14 Scheiben · 144 kcal · 12 g Protein",
    description:
      "Bienes Protein-Brot ohne Hefe, ohne Wartezeit, ohne Zucker. Tipp: in Scheiben einfrieren — hält am längsten. Wichtig: Sobald die Flüssigkeit zu den trockenen Zutaten kommt, muss das Brot in 3–5 Min im Ofen sein.",
    prepTime: 5,
    cookTime: 35,
    difficulty: "Einfach",
    servings: 14,
    tags: ["Anzeige", "ohne Zucker", "ohne Hefe", "High-Protein"],
    ingredients: [
      { amount: "250 ml", name: "Mandelmilch", note: "oder andere leichte Milch" },
      { amount: "2 EL", name: "(Apfel-)Essig" },
      { amount: "20 ml", name: "Olivenöl" },
      { amount: "120 ml", name: "Mineralwasser sprudelnd" },
      { amount: "350 g", name: "Dinkel- oder Weizenmehl" },
      { amount: "150 g", name: "MORE Total Protein", note: "geschmacksneutral oder Sahne" },
      { amount: "16 g", name: "Backpulver", note: "1 Packung" },
      { amount: "1 TL", name: "Salz" },
    ],
    steps: [
      "Milch lauwarm erwärmen, Essig dazu, umrühren, stehen lassen.",
      "Backofen auf 220 °C O/U vorheizen, eine Schale Wasser unten reinstellen.",
      "Trockene Zutaten in großer Schüssel vermengen.",
      "Zur Milch-Essig-Mischung Öl und Mineralwasser geben.",
      "WICHTIG: Ab jetzt schnell! Sobald die Flüssigkeit hinzukommt, sollte das Brot in 3–5 Min im Ofen sein.",
      "Milch-Mischung zu den trockenen Zutaten kippen, schnell mit Knethaken zu einem klebrigen Teig vermengen, in die Coox-Wunderform-M füllen.",
      "Mit Wasser bepinseln, einschneiden, mit Mehl durch ein Sieb bestäuben, ab in den Ofen!",
      "35 Min bei 220 °C O/U backen, herausnehmen, abkühlen lassen.",
    ],
    nutrition: {
      kcal: 144,
      protein: 12,
      carbs: 18,
      fat: 2,
    },
    sourceUrl: "https://www.instagram.com/reel/DWJU84joSW4/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },

  // ─── Pack 3: Bienes Snacks (5 Rezepte, original von @bienesfitlife) ───
  {
    slug: "frozen-coconut-strawberry-cups",
    packSlug: "blitz-snacks",
    number: 1,
    title: "Frozen Coconut & Strawberry Cups",
    subtitle: "8 Cups · 132 kcal · 7 g Protein",
    description:
      "Bienes perfekter kleiner Sommer-Snack — zwei Schichten (cremig Kokos + fruchtig Erdbeere), in 10 Min vorbereitet, dann ins Gefrierfach. Ohne Zuckerzusatz.",
    prepTime: 10,
    cookTime: 0,
    difficulty: "Einfach",
    servings: 8,
    tags: ["Anzeige", "ohne Zucker", "TK", "Protein"],
    ingredients: [
      { amount: "350 g", name: "TK-Erdbeeren", note: "Erdbeer-Schicht" },
      { amount: "1 Schuss", name: "Wasser", note: "Erdbeer-Schicht" },
      { amount: "1 Spritzer", name: "MORE Zerup Strawberry Sugar", note: "Erdbeer-Schicht · oder Süße nach Wahl" },
      { amount: "10 g", name: "Chiasamen", note: "Erdbeer-Schicht" },
      { amount: "80 g", name: "Kokosraspeln", note: "Kokos-Schicht" },
      { amount: "60 g", name: "MORE Sahne Protein", note: "Kokos-Schicht" },
      { amount: "3 g", name: "MORE Chunky White Almond Coconut", note: "Kokos-Schicht · oder andere Süße" },
      { amount: "80 ml", name: "Kokosmilch", note: "Kokos-Schicht · fettreduziert, aus der Dose" },
    ],
    steps: [
      "TK-Erdbeeren in einer Pfanne mit dem Schuss Wasser erhitzen.",
      "Währenddessen Kokosraspeln mit Protein, Kokosmilch und Chunky in einem Mixer fein mixen.",
      "Hitze aus, weiche Erdbeeren zerdrücken, süßen und mit Chiasamen verrühren.",
      "Kokosmasse auf 8 Muffinförmchen aufteilen, mit Erdbeer-Masse toppen.",
      "3–4 Stunden ins Gefrierfach — fertig!",
    ],
    nutrition: {
      kcal: 132,
      protein: 7,
      carbs: 6,
      fat: 9,
    },
    sourceUrl: "https://www.instagram.com/reel/DVgnNrPjCf5/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "protein-griesspudding",
    packSlug: "blitz-snacks",
    number: 2,
    title: "8-Min Protein-Grießpudding",
    subtitle: "1 Portion · 336 kcal · 33 g Protein",
    description:
      "Bienes 8-Min Grießpudding ohne Zucker — mit Vanille-Pudding-Pulver, MORE Sahne Protein und Chunky Vanilla Perfection. Am besten direkt warm genießen.",
    prepTime: 3,
    cookTime: 5,
    difficulty: "Einfach",
    servings: 1,
    tags: ["Anzeige", "ohne Zucker", "High-Protein", "Schnell"],
    ingredients: [
      { amount: "20 g", name: "Puddingpulver Vanille" },
      { amount: "300 ml", name: "Wasser", note: "kalt" },
      { amount: "50–100 ml", name: "Mandelmilch", note: "je nach gewünschter Cremigkeit" },
      { amount: "25 g", name: "(Dinkel-)Grieß" },
      { amount: "40 g", name: "MORE Protein Sahne" },
      { amount: "3 g", name: "MORE Chunky Vanilla Perfection" },
    ],
    steps: [
      "Puddingpulver mit dem kalten Wasser verrühren.",
      "Unter gelegentlichem Rühren aufkochen.",
      "In der Zeit Sahne Protein mit Mandelmilch verrühren und etwas andicken lassen.",
      "Wenn die Pudding-Masse kocht, Grieß hinzugeben und ca. 3 Min auf mittlerer Hitze köcheln lassen, dabei umrühren.",
      "Topf vom Herd, sofort das angedickte Protein einrühren. Mit Chunky süßen — am besten direkt noch warm genießen.",
    ],
    nutrition: {
      kcal: 336,
      protein: 33,
      carbs: 36,
      fat: 5,
    },
    sourceUrl: "https://www.instagram.com/reel/DUI_JRvDNLT/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "protein-kaiserschmarren",
    packSlug: "blitz-snacks",
    number: 3,
    title: "High Protein Kaiserschmarren",
    subtitle: "1 Portion · 431 kcal · 41 g Protein · 10 Min",
    description:
      "Bienes Kaiserschmarren in 10 Min — schmeckt wie das Original, macht satt und glücklich. Am besten mit Marmelade, Pudererythrit oder Apfelmus.",
    prepTime: 5,
    cookTime: 5,
    difficulty: "Einfach",
    servings: 1,
    tags: ["Anzeige", "ohne Zucker", "High-Protein", "Klassiker"],
    ingredients: [
      { amount: "40 g", name: "Dinkelmehl" },
      { amount: "30 g", name: "MORE Protein Sahne" },
      { amount: "3 g", name: "MORE Chunky Vanilla Perfection" },
      { amount: "2 g", name: "Backpulver" },
      { amount: "2", name: "Eier", note: "getrennt" },
      { amount: "90 ml", name: "Mandelmilch" },
      { amount: "etwas", name: "MORE 2 kcal Ölspray" },
      { amount: "etwas", name: "MORE no more Sugar pulverisiert", note: "oder Erythrit-Puder" },
    ],
    steps: [
      "Alle trockenen Zutaten vermengen.",
      "Eier trennen. Eiklar steif schlagen. Eigelb mit Mandelmilch zu den trockenen Zutaten geben und zu einem Teig verrühren.",
      "Eiklar vorsichtig unter den Teig heben, sodass er möglichst luftig flüssig bleibt.",
      "Pfanne auf mittlerer Hitze erwärmen, mit Ölspray besprühen. Teig hineingeben und mit Deckel ca. 2–3 Min anbraten.",
      "Teig wenden, nochmals kurz anbraten, dann mit einem Pfannenwender in die typischen Kaiserschmarren-Stücke rupfen.",
      "Mit Marmelade, Pudererythrit oder Apfelmus servieren.",
    ],
    nutrition: {
      kcal: 431,
      protein: 41,
      carbs: 33,
      fat: 14,
    },
    sourceUrl: "https://www.instagram.com/reel/DTdkfAajIoZ/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "marzipankartoffeln",
    packSlug: "blitz-snacks",
    number: 4,
    title: "5-Min Marzipankartoffeln",
    subtitle: "22 Kugeln · 17 kcal · 1,3 g Protein pro Stück",
    description:
      "Bienes zuckerfreie Marzipankartoffeln — pro Kugel nur 17 kcal. Tipp: kühl gelagert halten sie sich mehrere Tage. Funktioniert auch mit jedem anderen Chunky-Flavour.",
    prepTime: 5,
    cookTime: 0,
    difficulty: "Einfach",
    servings: 22,
    tags: ["Anzeige", "ohne Zucker", "Mini-Snack", "Mealprep-tauglich"],
    ingredients: [
      { amount: "40 g", name: "gemahlene blanchierte Mandeln" },
      { amount: "25 g", name: "MORE Protein Sahne" },
      { amount: "20 g", name: "no more Sugar", note: "im Mixer pulverisiert · oder Erythrit" },
      { amount: "3 g", name: "MORE Chunky Morezipan White Chocolate" },
      { amount: "20 ml", name: "Mandelmilch ungesüßt" },
      { amount: "ca. 2 g", name: "Backkakao", note: "Topping" },
      { amount: "ca. 2 g", name: "MORE Chunky Feine Vollmilch Schokolade", note: "Topping" },
    ],
    steps: [
      "Alle Zutaten für die Kartoffeln mit den Händen zu einer Teigkugel verkneten.",
      "Teig in 22 gleichschwere Teile (je 5 g) teilen und zu Kugeln rollen.",
      "Kugeln in einer Mischung aus Backkakao und Chunky schwenken — fertig!",
      "Am besten kühl stellen — so halten sie mehrere Tage.",
    ],
    nutrition: {
      kcal: 17,
      protein: 1,
      carbs: 0,
      fat: 1,
    },
    sourceUrl: "https://www.instagram.com/reel/DRUJkzxDA99/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "zimt-streuseltaler",
    packSlug: "blitz-snacks",
    number: 5,
    title: "Schnelle Zimt-Streuseltaler",
    subtitle: "4 Stück · 222 kcal · 19 g Protein (ohne Obst)",
    description:
      "Bienes Streuseltaler wie vom Bäcker — nur ohne Zucker und 3× weniger kcal. Mit Pflaumen oder anderem Obst nach Wahl, in 10 Min im Ofen.",
    prepTime: 10,
    cookTime: 20,
    difficulty: "Einfach",
    servings: 4,
    tags: ["Anzeige", "ohne Zucker", "High-Protein", "Bäcker-Klassiker"],
    ingredients: [
      { amount: "80 g", name: "Dinkelmehl Type 630", note: "Teig" },
      { amount: "40 g", name: "MORE Total Protein Sahne", note: "Teig" },
      { amount: "8 g", name: "Backpulver", note: "Teig" },
      { amount: "5 g", name: "MORE Chunky Vanilla Perfection", note: "Teig" },
      { amount: "140 g", name: "Magerquark", note: "Teig" },
      { amount: "200 g", name: "Pflaumen", note: "Topping · oder Obst nach Wahl" },
      { amount: "35 g", name: "Dinkelmehl Type 630", note: "Streusel" },
      { amount: "20 g", name: "MORE Total Protein Sahne", note: "Streusel" },
      { amount: "20 g", name: "Erythrit", note: "Streusel" },
      { amount: "3 g", name: "MORE Chunky Vanilla Perfection", note: "Streusel" },
      { amount: "1 Prise", name: "Zimt", note: "Streusel · gerne großzügig" },
      { amount: "25 g", name: "Meggle Joghurt-Butter", note: "Streusel" },
    ],
    steps: [
      "Trockene Zutaten für den Teig vermengen, mit Magerquark verkneten.",
      "Teig in 4 gleichgroße Kugeln teilen, auf einer Backmatte zu Kreisen platt drücken.",
      "Mit Obst nach Wahl belegen.",
      "Streusel-Zutaten zusammenkneten, auf dem Obst verteilen.",
      "Bei 175 °C Umluft ca. 20 Min backen — nach 10 Min mit Alufolie abdecken, damit sie nicht zu braun werden.",
    ],
    nutrition: {
      kcal: 222,
      protein: 19,
      carbs: 23,
      fat: 6,
    },
    sourceUrl: "https://www.instagram.com/reel/DOgp5oyiIE0/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },

  // ─── Pack 4: Volumen-Wunder (5 Rezepte, original von @bienesfitlife) ───
  {
    slug: "kaese-zucchini-frittata",
    packSlug: "volumen-wunder",
    number: 1,
    title: "Käse-Zucchini-Frittata",
    subtitle: "1 Schüssel · 404 kcal · 35 g Protein",
    description:
      "Bienes Frittata-Bowl als perfektes Abnehm-Mealprep. Schmeckt warm und kalt, eine ganze Schüssel mit nur 404 kcal — die perfekte kleine WPF-Mahlzeit.",
    prepTime: 10,
    cookTime: 25,
    difficulty: "Einfach",
    servings: 1,
    tags: ["Anzeige", "High-Protein", "WPF-Mahlzeit", "Mealprep", "Low-Carb"],
    ingredients: [
      { amount: "2", name: "Eier" },
      { amount: "40 g", name: "Salakis Feta Light" },
      { amount: "200 g", name: "Zucchini", note: "gerieben, leicht ausgedrückt" },
      { amount: "Gewürze", name: "z. B. MORE Knobilicious" },
      { amount: "40 g", name: "Reibekäse Light" },
    ],
    steps: [
      "Eier mit zerbröseltem Feta in einer ofenfesten Schüssel verrühren.",
      "Zucchini klein reiben, leicht ausdrücken, mit in die Schüssel geben. Würzen und verrühren.",
      "Mit Käse toppen und für 20–25 Min bei 175 °C Umluft in den Ofen.",
    ],
    nutrition: {
      kcal: 404,
      protein: 35,
      carbs: 6,
      fat: 24,
    },
    sourceUrl: "https://www.instagram.com/reel/DUWJLygjmS9/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "viral-xl-gemuese-wrap",
    packSlug: "volumen-wunder",
    number: 2,
    title: "Viraler XL Gemüse-Wrap",
    subtitle: "2 Portionen · 435 kcal · 42 g Protein (mit Füllung)",
    description:
      "Bienes virale XL-Wrap-Rolle aus Zucchini, Kartoffel und Karotte — das ganze Blech ergibt 2 Portionen. Mit Füllung 435 kcal, ohne Füllung 360 kcal pro Portion.",
    prepTime: 10,
    cookTime: 30,
    difficulty: "Einfach",
    servings: 2,
    tags: ["Anzeige", "High-Protein", "WPF-Mahlzeit", "XL", "viral"],
    ingredients: [
      { amount: "350 g", name: "Zucchini", note: "Teig · roh, fein geraspelt" },
      { amount: "150 g", name: "Kartoffel", note: "Teig · roh, fein geraspelt" },
      { amount: "100 g", name: "Karotte", note: "Teig · roh, fein geraspelt" },
      { amount: "80 g", name: "Käse", note: "Teig · gerieben, light" },
      { amount: "20 g", name: "MORE Protein Sahne", note: "Teig" },
      { amount: "3", name: "Eier", note: "Teig · M" },
      { amount: "Gewürze", name: "z. B. Salz + MORE Knobilicious", note: "Teig" },
      { amount: "Eisbergsalat", name: "nach Wahl", note: "Füllung" },
      { amount: "100 g", name: "Exquisa fitline 0,2 %", note: "Füllung" },
      { amount: "100 g", name: "Cocktail-Tomaten", note: "Füllung" },
      { amount: "40 g", name: "Feta Light", note: "Füllung" },
      { amount: "MORE Light Gourmet Sauce Chipotle", name: "nach Wahl", note: "Füllung" },
    ],
    steps: [
      "Zucchini, Karotte und Kartoffel roh fein raspeln, Flüssigkeit so gut es geht ausdrücken.",
      "Mit Eiern, Sahne Protein und Gewürzen zu einem Teig verrühren, auf Backpapier glatt ausstreichen.",
      "Bei 180 °C Umluft 25–30 Min backen, schön goldbraun werden lassen.",
      "Etwas abkühlen lassen, mit Salat, Frischkäse, Tomaten, Feta und Sauce belegen, einrollen.",
      "Die Hälfte der XL-Rolle ist eine Portion!",
    ],
    nutrition: {
      kcal: 435,
      protein: 42,
      carbs: 32,
      fat: 17,
    },
    sourceUrl: "https://www.instagram.com/reel/DPWwnKgCLAS/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "lebensveraendernder-salat",
    packSlug: "volumen-wunder",
    number: 3,
    title: "Lebensverändernder Salat",
    subtitle: "1 Portion · 394 kcal · 35 g Protein",
    description:
      "Der virale 'wegen-dem-Salat-hat-sie-ihren-Mann-geheiratet'-Salat — von Biene getestet und als 'lebensverändernd lecker' bestätigt. Mit gekochtem Ei, Veggie-Chicken und Feta zur perfekten kleinen WPF-Mahlzeit gepimpt.",
    prepTime: 10,
    cookTime: 5,
    difficulty: "Einfach",
    servings: 1,
    tags: ["Anzeige", "High-Protein", "WPF-Mahlzeit", "Salat", "viral"],
    ingredients: [
      { amount: "150 g", name: "Eisbergsalat" },
      { amount: "1/2", name: "Zitrone", note: "Saft" },
      { amount: "15 ml", name: "Olivenöl" },
      { amount: "gute Menge", name: "Salz" },
      { amount: "Gewürze", name: "z. B. MORE Knobilicious oder Pfeffer" },
      { amount: "1 Zehe", name: "Knoblauch" },
      { amount: "1–2 EL", name: "Essig" },
      { amount: "1", name: "Ei", note: "Pimp · gekocht" },
      { amount: "90 g", name: "Veggie-Chicken", note: "Pimp · angebraten" },
      { amount: "30 g", name: "Salakis Feta Light", note: "Pimp" },
      { amount: "100 g", name: "Cocktail-Tomaten", note: "Pimp" },
    ],
    steps: [
      "Eisbergsalat klein zupfen.",
      "Zitronensaft, Olivenöl, Salz, Gewürze, gepressten Knoblauch und Essig zu einem Dressing verrühren.",
      "Veggie-Chicken anbraten, Ei kochen.",
      "Alles in eine Schüssel geben — Salat, gekochtes Ei, Veggie-Chicken, Feta, Cocktail-Tomaten — mit dem Dressing vermengen.",
    ],
    nutrition: {
      kcal: 394,
      protein: 35,
      carbs: 8,
      fat: 24,
    },
    sourceUrl: "https://www.instagram.com/reel/DNgStM8MSZF/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "beeren-cookie-crumble",
    packSlug: "volumen-wunder",
    number: 4,
    title: "Beeren-Cookie-Crumble",
    subtitle: "1 Portion · 435 kcal · 33 g Protein",
    description:
      "Bienes Frühstück für Beeren- und Keksteig-Lover — Beerenmasse mit Keksteig-Topping überbacken. Eine ganze Auflaufform = 1 perfekte kleine WPF-Mahlzeit.",
    prepTime: 5,
    cookTime: 20,
    difficulty: "Einfach",
    servings: 1,
    tags: ["Anzeige", "ohne Zucker", "High-Protein", "WPF-Mahlzeit", "Frühstück"],
    ingredients: [
      { amount: "300 g", name: "TK-Beerenmix", note: "Beerenmasse" },
      { amount: "10 g", name: "Speisestärke", note: "Beerenmasse" },
      { amount: "3 g", name: "MORE Chunky Vanilla Perfection", note: "Beerenmasse" },
      { amount: "20 g", name: "no more Sugar", note: "Beerenmasse · Erythrit-Stevia-Mix" },
      { amount: "40 g", name: "Dinkelmehl", note: "Keksteig" },
      { amount: "25 g", name: "MORE Protein Sahne", note: "Keksteig" },
      { amount: "3 g", name: "MORE Chunky Vanilla Perfection", note: "Keksteig" },
      { amount: "40 g", name: "no more Sugar", note: "Keksteig · Erythrit-Stevia-Mix" },
      { amount: "20 ml", name: "Mandelmilch", note: "Keksteig" },
      { amount: "50 g", name: "Magerquark", note: "Keksteig" },
    ],
    steps: [
      "TK-Beeren auftauen, leicht erwärmt in eine Auflaufform geben. Backofen auf 175 °C Umluft vorheizen.",
      "Speisestärke, Erythrit und Chunky unter die Beeren rühren.",
      "Keksteig aus den Zutaten anrühren und auf den Beeren verstreichen.",
      "15–20 Min überbacken bis goldbraun — fertig!",
    ],
    nutrition: {
      kcal: 435,
      protein: 33,
      carbs: 56,
      fat: 3,
    },
    sourceUrl: "https://www.instagram.com/reel/DK2Yk1QoBJs/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "xxl-frueh-cookie",
    packSlug: "volumen-wunder",
    number: 5,
    title: "XXL Frühstücks-Cookie",
    subtitle: "1 XL-Cookie · 444 kcal · 36 g Protein · 5 Min",
    description:
      "Bienes XXL-Cookie als Abnehm-Frühstück — eine ganze 18er-Coox-Wunderform für 1 Portion. In 15 Min im Ofen und mit MORE Schoko Drops.",
    prepTime: 5,
    cookTime: 15,
    difficulty: "Einfach",
    servings: 1,
    tags: ["Anzeige", "High-Protein", "WPF-Mahlzeit", "Frühstück", "Schnell"],
    ingredients: [
      { amount: "45 g", name: "Haferflocken", note: "gemahlen" },
      { amount: "20 g", name: "MORE Protein Sahne" },
      { amount: "3 g", name: "Backpulver" },
      { amount: "1", name: "Ei" },
      { amount: "3 g", name: "MORE Chunky Flavour", note: "nach Wahl" },
      { amount: "60 g", name: "Magerquark" },
      { amount: "20 g", name: "Mandelmilch" },
      { amount: "10 g", name: "MORE Schoko Drops" },
    ],
    steps: [
      "Alle Zutaten vermengen.",
      "Schoko Drops unterheben.",
      "Bei 175 °C Umluft ca. 15 Min in der 18er Coox-Wunderform backen.",
    ],
    nutrition: {
      kcal: 444,
      protein: 36,
      carbs: 38,
      fat: 15,
    },
  },

  // ─── Pack 5: Meal-Prep Heroes (7 Rezepte) ───
  {
    slug: "schoko-overnight-oats",
    packSlug: "meal-prep-heroes",
    number: 1,
    title: "Schoko-Overnight-Oats",
    subtitle: "Vorbereitet · 28 g Eiweiß",
    description:
      "Über Nacht eingeweicht, morgens fertig — Haferflocken, Schoko-Whey und Beeren in der Glasdose.",
    prepTime: 5,
    difficulty: "Einfach",
    servings: 1,
    tags: ["Mealprep", "Frühstück"],
    ingredients: [
      { amount: "60 g", name: "Haferflocken" },
      { amount: "200 ml", name: "Mandelmilch" },
      { amount: "30 g", name: "Schoko-Whey" },
      { amount: "100 g", name: "Beeren" },
      { amount: "1 TL", name: "Chiasamen" },
    ],
    steps: [
      "Alle Zutaten in ein Weckglas geben, gut vermengen.",
      "Über Nacht in den Kühlschrank stellen.",
      "Morgens umrühren, optional mit weiteren Beeren toppen.",
    ],
    nutrition: {
      kcal: 380,
      protein: 32,
      carbs: 42,
      fat: 7,
      fiber: 8,
    },
  },
  {
    slug: "fuenf-schicht-salat",
    packSlug: "meal-prep-heroes",
    number: 2,
    title: "5-Schicht-Salat",
    subtitle: "Vorbereitet · hält 4 Tage",
    description:
      "Quinoa, Hähnchen, Kichererbsen, Gemüse und Joghurt-Dressing — alles in einem Glas geschichtet.",
    prepTime: 20,
    cookTime: 10,
    difficulty: "Einfach",
    servings: 4,
    tags: ["Mealprep", "Salat"],
    ingredients: [
      { amount: "200 g", name: "Quinoa", note: "gekocht" },
      { amount: "400 g", name: "Hähnchenbrust" },
      { amount: "1 Dose", name: "Kichererbsen" },
      { amount: "200 g", name: "Cherrytomaten" },
      { amount: "1", name: "Gurke" },
      { amount: "200 g", name: "Magerjoghurt" },
      { amount: "1 EL", name: "Olivenöl" },
      { amount: "Zitrone", name: "& Kräuter" },
    ],
    steps: [
      "Hähnchen würfeln und braten.",
      "Joghurt mit Olivenöl, Zitrone und Kräutern zu einem Dressing verrühren.",
      "In 4 Gläsern schichten: Dressing → Quinoa → Hähnchen → Kichererbsen → Tomaten/Gurke.",
      "Im Kühlschrank lagern, vor dem Verzehr durchschütteln.",
    ],
    nutrition: {
      kcal: 420,
      protein: 38,
      carbs: 40,
      fat: 10,
      fiber: 9,
    },
  },
  {
    slug: "asia-bowl-meal-prep",
    packSlug: "meal-prep-heroes",
    number: 3,
    title: "Asia-Bowl Meal Prep",
    subtitle: "Vorbereitet · für 4 Tage",
    description:
      "Reis, Edamame, Tofu und Sesam — vorbereitet für die ganze Woche, mit pikantem Erdnuss-Dressing.",
    prepTime: 20,
    cookTime: 15,
    difficulty: "Einfach",
    servings: 4,
    tags: ["Mealprep", "Asia", "Vegetarisch"],
    ingredients: [
      { amount: "300 g", name: "Reis", note: "gekocht" },
      { amount: "300 g", name: "Räuchertofu" },
      { amount: "200 g", name: "Edamame" },
      { amount: "2", name: "Karotten" },
      { amount: "60 g", name: "Erdnussbutter" },
      { amount: "2 EL", name: "Sojasauce" },
      { amount: "1 EL", name: "Limettensaft" },
    ],
    steps: [
      "Tofu würfeln und knusprig braten.",
      "Karotten julienneartig schneiden.",
      "Erdnussbutter, Sojasauce und Limettensaft zu einem Dressing verrühren.",
      "In 4 Boxen schichten: Reis, Tofu, Edamame, Karotten — Dressing extra.",
    ],
    nutrition: {
      kcal: 480,
      protein: 32,
      carbs: 50,
      fat: 16,
      fiber: 8,
    },
  },
  {
    slug: "reis-bowl-curry",
    packSlug: "meal-prep-heroes",
    number: 4,
    title: "Reis-Bowl Curry",
    subtitle: "Vorbereitet · 32 g Eiweiß",
    description:
      "Mildes Hähnchen-Curry mit Kokosmilch und Reis — wärmt schön von innen, perfekt für die Mittagspause.",
    prepTime: 15,
    cookTime: 25,
    difficulty: "Einfach",
    servings: 4,
    tags: ["Mealprep", "Curry"],
    ingredients: [
      { amount: "500 g", name: "Hähnchenbrust" },
      { amount: "400 ml", name: "Kokosmilch light" },
      { amount: "2 EL", name: "Currypaste mild" },
      { amount: "300 g", name: "Reis", note: "gekocht" },
      { amount: "2", name: "Paprika" },
      { amount: "1", name: "Zwiebel" },
      { amount: "Koriander", name: "frisch" },
    ],
    steps: [
      "Zwiebel und Paprika anbraten.",
      "Hähnchen würfeln, zugeben, mit Currypaste anrösten.",
      "Mit Kokosmilch ablöschen, 15 Minuten köcheln lassen.",
      "Mit Reis in 4 Boxen verteilen, mit Koriander garnieren.",
    ],
    nutrition: {
      kcal: 510,
      protein: 42,
      carbs: 48,
      fat: 13,
      fiber: 5,
    },
  },
  {
    slug: "bulgur-salat",
    packSlug: "meal-prep-heroes",
    number: 5,
    title: "Bulgur-Salat",
    subtitle: "Vorbereitet · vegetarisch · sättigend",
    description:
      "Bulgur, Feta, Granatapfel und viel Petersilie — orientalisch inspiriert und super frisch.",
    prepTime: 15,
    difficulty: "Einfach",
    servings: 4,
    tags: ["Mealprep", "Vegetarisch", "Mediterran"],
    ingredients: [
      { amount: "200 g", name: "Bulgur" },
      { amount: "200 g", name: "Feta light" },
      { amount: "1", name: "Granatapfel" },
      { amount: "1 Bund", name: "Petersilie" },
      { amount: "1", name: "Gurke" },
      { amount: "2 EL", name: "Olivenöl" },
      { amount: "1", name: "Zitrone" },
    ],
    steps: [
      "Bulgur nach Packungsanleitung kochen, abkühlen lassen.",
      "Feta würfeln, Granatapfelkerne, gehackte Petersilie und Gurke zugeben.",
      "Mit Olivenöl, Zitronensaft, Salz und Pfeffer abschmecken.",
      "In 4 Boxen verteilen, hält 4 Tage im Kühlschrank.",
    ],
    nutrition: {
      kcal: 380,
      protein: 18,
      carbs: 42,
      fat: 14,
      fiber: 8,
    },
  },
  {
    slug: "quinoa-box",
    packSlug: "meal-prep-heroes",
    number: 6,
    title: "Quinoa-Power-Box",
    subtitle: "Vorbereitet · 38 g Eiweiß",
    description:
      "Quinoa, Süßkartoffel, Lachs und Spinat in einer Box — Omega-3 für die Bürowoche.",
    prepTime: 15,
    cookTime: 25,
    difficulty: "Mittel",
    servings: 4,
    tags: ["Mealprep", "Omega-3"],
    ingredients: [
      { amount: "200 g", name: "Quinoa" },
      { amount: "2", name: "Süßkartoffeln" },
      { amount: "400 g", name: "Lachsfilet" },
      { amount: "200 g", name: "Babyspinat" },
      { amount: "1", name: "Zitrone" },
      { amount: "1 EL", name: "Olivenöl" },
    ],
    steps: [
      "Süßkartoffeln würfeln und 25 Minuten bei 200 °C rösten.",
      "Quinoa kochen, Lachs in der Pfanne braten.",
      "In 4 Boxen schichten: Quinoa, Süßkartoffel, Spinat, Lachs.",
      "Mit Zitronenscheibe und Olivenöl-Drizzle servieren.",
    ],
    nutrition: {
      kcal: 520,
      protein: 38,
      carbs: 48,
      fat: 18,
      fiber: 8,
    },
  },
  {
    slug: "haehnchen-wraps",
    packSlug: "meal-prep-heroes",
    number: 7,
    title: "Hähnchen-Wraps",
    subtitle: "Vorbereitet · handlich · 35 g Eiweiß",
    description:
      "Vollkorn-Wraps mit Hähnchen, Avocado, Salat und Joghurt-Sauce — fertig zum Einpacken.",
    prepTime: 15,
    cookTime: 10,
    difficulty: "Einfach",
    servings: 4,
    tags: ["Mealprep", "Handheld"],
    ingredients: [
      { amount: "4", name: "Vollkorn-Wraps" },
      { amount: "400 g", name: "Hähnchenbrust" },
      { amount: "1", name: "Avocado" },
      { amount: "Salat", name: "nach Wahl" },
      { amount: "200 g", name: "Magerjoghurt" },
      { amount: "1 TL", name: "Senf" },
    ],
    steps: [
      "Hähnchen würzen, in Streifen braten, abkühlen lassen.",
      "Joghurt mit Senf verrühren, auf den Wraps verstreichen.",
      "Hähnchen, Avocado-Scheiben und Salat darauf verteilen.",
      "Fest aufrollen, in Folie einwickeln, hält 2 Tage.",
    ],
    nutrition: {
      kcal: 410,
      protein: 38,
      carbs: 35,
      fat: 13,
      fiber: 6,
    },
  },
];

export function getRecipesForPack(packSlug: string): Recipe[] {
  return recipes
    .filter((recipe) => recipe.packSlug === packSlug)
    .sort((a, b) => a.number - b.number);
}

export function getRecipe(packSlug: string, recipeSlug: string): Recipe | undefined {
  return recipes.find(
    (recipe) => recipe.packSlug === packSlug && recipe.slug === recipeSlug
  );
}
