export type Ingredient = {
  amount: string;
  name: string;
  note?: string;
};

export type Micronutrient = {
  name: string;
  amount: string;
  pctDaily?: number;
};

export type Nutrition = {
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber?: number;
  sugar?: number;
  micros?: Micronutrient[];
};

export type Recipe = {
  slug: string;
  packSlug: string;
  number: number;
  title: string;
  subtitle: string;
  description: string;
  prepTime: number;
  cookTime?: number;
  difficulty: "Einfach" | "Mittel" | "Aufwendig";
  servings: number;
  tags: string[];
  ingredients: Ingredient[];
  steps: string[];
  nutrition: Nutrition;
  hero?: string;
  sourceUrl?: string;
  sourceLabel?: string;
};

export const recipes: Recipe[] = [
  // ─── Pack 1: Feierabend-Klassiker (7 Rezepte, original von @bienesfitlife) ───
  {
    slug: "kartoffelsalat-protein-mayo",
    packSlug: "feierabend-klassiker",
    number: 1,
    title: "Kartoffelsalat mit Protein-Mayo",
    subtitle: "5 große Portionen · 313 kcal · 1345 kcal gespart",
    description:
      "Bienes Klassiker für die Grillfeier — die cremige Mayo wird komplett aus hartgekochten Eiern gemixt. Niemand merkt, dass wir hier 1345 kcal sparen.",
    prepTime: 15,
    cookTime: 25,
    difficulty: "Einfach",
    servings: 5,
    tags: ["Anzeige", "High-Protein", "Grillklassiker", "Mealprep-tauglich"],
    ingredients: [
      { amount: "1000 g", name: "Kartoffeln" },
      { amount: "200 g", name: "Gewürzgurken" },
      { amount: "4", name: "Eier", note: "gekocht" },
      { amount: "Salz", name: "& Knobilicious-Gewürz" },
      { amount: "1 Bund", name: "Petersilie & Schnittlauch", note: "frisch" },
      { amount: "3", name: "Eier", note: "für die Mayo · hartgekocht" },
      { amount: "15 ml", name: "Öl", note: "für die Mayo · nach Wahl" },
      { amount: "50 ml", name: "Wasser", note: "für die Mayo" },
      { amount: "10 g", name: "Senf", note: "für die Mayo" },
      { amount: "1 Prise", name: "Salz", note: "für die Mayo" },
      { amount: "1 Spritzer", name: "Zitronensaft", note: "für die Mayo" },
      { amount: "20 g", name: "MORE Sahne Protein", note: "Geheimtipp · optional" },
    ],
    steps: [
      "Kartoffeln und Eier kochen. Kartoffeln pellen und abkühlen lassen, in der Zeit Gurken und Eier klein schneiden.",
      "Die Kartoffeln ebenfalls würfeln und alles in eine Schale geben.",
      "Für die Mayo alle Zutaten in einen Mixer geben — die Eier zuerst, dann alles cremig mixen. Optional 20 g MORE Sahne Protein für Extra-Cremigkeit & Sättigung.",
      "Mayo unter den Kartoffelsalat heben, mit Petersilie und Schnittlauch toppen, durchmischen und genießen!",
    ],
    nutrition: {
      kcal: 313,
      protein: 15,
      carbs: 34,
      fat: 12,
      fiber: 4,
    },
    sourceUrl: "https://www.instagram.com/reel/DW_GD7buV5s/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "kaese-nudeln",
    packSlug: "feierabend-klassiker",
    number: 2,
    title: "Käse-Nudeln zum Abnehmen",
    subtitle: "2 Portionen · 726 kcal · 51 g Protein · 15 Min",
    description:
      "Bienes virale Käse-Nudel-Pfanne — Schmelzkäse, MORE Trüffel-Mayo und Sahne Protein machen sie cremig wie Carbonara. Die perfekte große WPF-Mahlzeit für alle Käse-Nudel-Fans.",
    prepTime: 5,
    cookTime: 10,
    difficulty: "Einfach",
    servings: 2,
    tags: ["Anzeige", "High-Protein", "WPF-Mahlzeit", "Schnell"],
    ingredients: [
      { amount: "3 Scheiben", name: "Schmelzkäse" },
      { amount: "20 g", name: "Light Butter" },
      { amount: "1 EL", name: "Tomatenmark" },
      { amount: "1 EL", name: "MORE Light Gourmet Sauce", note: "z. B. Trüffel-Mayo" },
      { amount: "1 TL", name: "Gemüsebrühe-Gewürz" },
      { amount: "Gewürze", name: "z. B. MORE Pasta Allrounder" },
      { amount: "500 ml", name: "Mandelmilch ungesüßt" },
      { amount: "180 g", name: "Mie-Nudeln" },
      { amount: "etwas", name: "Salz" },
      { amount: "70 g", name: "MORE Sahne Protein" },
      { amount: "100 ml", name: "Mandelmilch", note: "für die Protein-Sahne" },
      { amount: "Petersilie", name: "frisch" },
      { amount: "2 Scheiben", name: "Schmelzkäse", note: "Topping · 1 pro Schüssel" },
    ],
    steps: [
      "3 Scheiben Schmelzkäse mit Butter, Tomatenmark, Mayo und Gewürzen in einer Pfanne bei mittlerer Hitze schmelzen.",
      "Mit 500 ml Mandelmilch ablöschen, gut verrühren, dann die Mie-Nudeln hineingeben. Mit Deckel 10 Minuten köcheln lassen, ggf. einmal wenden.",
      "In der Kochzeit Sahne Protein mit 100 ml Mandelmilch anrühren. Nudeln in der Pfanne vermengen, Hitze aus, Protein-Sahne unterziehen.",
      "Auf zwei Schüsseln verteilen, mit je einer Scheibe Schmelzkäse toppen und Petersilie servieren.",
    ],
    nutrition: {
      kcal: 726,
      protein: 51,
      carbs: 75,
      fat: 24,
      fiber: 4,
    },
    sourceUrl: "https://www.instagram.com/reel/DV9J1iBDuIJ/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "blech-pasta",
    packSlug: "feierabend-klassiker",
    number: 3,
    title: "Blech-Pasta",
    subtitle: "2 Portionen · 692 kcal · 53 g Protein",
    description:
      "Spaghetti, Salakis Feta und Cocktail-Tomaten aufs Blech — der Ofen macht den Rest. In 5 Minuten vorbereitet, perfekt als Mealprep.",
    prepTime: 5,
    cookTime: 25,
    difficulty: "Einfach",
    servings: 2,
    tags: ["Anzeige", "High-Protein", "WPF-Mahlzeit", "Mealprep"],
    ingredients: [
      { amount: "200 g", name: "Spaghetti", note: "ungekocht gewogen" },
      { amount: "180 g", name: "Salakis Feta Light" },
      { amount: "400 g", name: "Cocktail-Tomaten" },
      { amount: "1", name: "Zwiebel", note: "klein, gehackt" },
      { amount: "600–800 ml", name: "Gemüsebrühe" },
      { amount: "40 g", name: "Tomatenmark" },
      { amount: "Gewürze", name: "z. B. MORE Italian Allrounder" },
      { amount: "50 g", name: "MORE Sahne Protein" },
      { amount: "100 ml", name: "Mandelmilch", note: "für die Protein-Sahne" },
    ],
    steps: [
      "Backofen auf 180 °C Ober-/Unterhitze vorheizen.",
      "Gemüsebrühe zum Kochen bringen und Tomatenmark einrühren.",
      "Spaghetti aufs Blech verteilen, mit Feta, halbierten Cocktail-Tomaten und gehackter Zwiebel toppen, mit der Brühe übergießen und ca. 25 Min bei 180 °C backen.",
      "In der Zeit Sahne Protein mit Mandelmilch anrühren. Nach dem Backen mit der Protein-Sauce und Gewürzen vermengen.",
    ],
    nutrition: {
      kcal: 692,
      protein: 53,
      carbs: 92,
      fat: 12,
      fiber: 6,
    },
    sourceUrl: "https://www.instagram.com/reel/DVTnnPEDJPz/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "virale-pasta-pfanne",
    packSlug: "feierabend-klassiker",
    number: 4,
    title: "Virale Pasta-Pfanne",
    subtitle: "2 Portionen · 750 kcal · 54 g Protein",
    description:
      "Tomaten, Zwiebeln und Veggie-Hack zu Pasta-Sauce gedünstet — mit Käse, Nudeln und MORE Sahne Protein zur perfekten großen WPF-Mahlzeit.",
    prepTime: 10,
    cookTime: 20,
    difficulty: "Einfach",
    servings: 2,
    tags: ["Anzeige", "High-Protein", "WPF-Mahlzeit", "Sattmacher"],
    ingredients: [
      { amount: "5–6", name: "große Tomaten" },
      { amount: "etwas", name: "Ölspray" },
      { amount: "1", name: "Zwiebel", note: "gehackt" },
      { amount: "250 g", name: "Veggie-Hack", note: "oder normales Hack" },
      { amount: "1 Schuss", name: "Wasser" },
      { amount: "1 EL", name: "Tomatenmark" },
      { amount: "Gewürze", name: "z. B. MORE Pasta Allrounder" },
      { amount: "100 g", name: "geriebener Käse Light" },
      { amount: "180 g", name: "Nudeln", note: "ungekocht gewogen" },
      { amount: "20 g", name: "MORE Sahne Protein" },
      { amount: "50–80 ml", name: "Mandelmilch", note: "für die Protein-Sahne" },
      { amount: "Basilikum", name: "frisch" },
    ],
    steps: [
      "Tomaten in etwas Ölspray mit Wasser und gehackten Zwiebeln bei mittlerer Hitze mit Deckel ca. 10 Min dünsten.",
      "Hack zugeben und anbraten. Bei den Tomaten die Haut abziehen und sie kleindrücken.",
      "Mit Tomatenmark abschmecken, würzen, Käse einrühren.",
      "Mit gekochten Nudeln vermengen und mit Sahne Protein und etwas Käse toppen. Hitze aus, kurz ziehen lassen — fertig!",
    ],
    nutrition: {
      kcal: 750,
      protein: 54,
      carbs: 87,
      fat: 23,
      fiber: 7,
    },
    sourceUrl: "https://www.instagram.com/reel/DU_csfmDmzO/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "viral-cloud-wrap",
    packSlug: "feierabend-klassiker",
    number: 5,
    title: "Viral Cloud Wrap",
    subtitle: "1 XL-Wrap · 235 kcal Basis · 28 g Protein",
    description:
      "Eiklar-Wrap aus dem Ofen — XL-Mahlzeit, super sättigend und nur knapp 200 kcal als Basis. Perfekt für Volumen-Lover, die abnehmen wollen.",
    prepTime: 5,
    cookTime: 10,
    difficulty: "Einfach",
    servings: 1,
    tags: ["XL-Mahlzeit", "Volumen", "Low-Carb", "High-Protein"],
    ingredients: [
      { amount: "225 ml", name: "Eiklar" },
      { amount: "10 g", name: "Speisestärke" },
      { amount: "Salz", name: "" },
      { amount: "Gewürze", name: "z. B. MORE Knobilicious" },
      { amount: "50 g", name: "Exquisa fitline", note: "Belag" },
      { amount: "Eisbergsalat", name: "nach Wahl · Belag" },
      { amount: "1", name: "Spiegelei", note: "Belag" },
      { amount: "1", name: "große Tomate", note: "Belag" },
      { amount: "35 g", name: "Light Gouda", note: "Belag" },
      { amount: "MORE Light Gourmet Sauce", name: "Honey Mustard + Trüffel-Mayo · Belag" },
    ],
    steps: [
      "Backofen auf 180 °C Umluft vorheizen.",
      "Eiklar sehr steif schlagen, dann Speisestärke und Gewürze einrieseln lassen und vorsichtig unterheben.",
      "Auf einem Backpapier auf Backblechgröße verstreichen und 8–10 Min bei 180 °C backen, bis es leicht goldbraun, aber noch nicht knusprig fest ist.",
      "Vom Backpapier vorsichtig lösen, mit Frischkäse, Gouda, Tomate, Spiegelei, Salat und Saucen belegen — fertig!",
    ],
    nutrition: {
      kcal: 235,
      protein: 28,
      carbs: 11,
      fat: 8,
    },
    sourceUrl: "https://www.instagram.com/reel/DUqnNhMjIKL/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "blitz-cheeseburger-auflauf",
    packSlug: "feierabend-klassiker",
    number: 6,
    title: "Blitz Cheeseburger-Auflauf",
    subtitle: "2 Portionen · 683 kcal · 53 g Protein",
    description:
      "Kartoffeln, Veggie-Hack und Burger-Sauce mit Schmelzkäse überbacken — schmeckt nach purer Sünde, ist aber Abnehm-Mealprep für 2 Tage.",
    prepTime: 10,
    cookTime: 15,
    difficulty: "Einfach",
    servings: 2,
    tags: ["Anzeige", "High-Protein", "Sattmacher", "Mealprep"],
    ingredients: [
      { amount: "600 g", name: "Kartoffeln", note: "roh gewogen" },
      { amount: "250 g", name: "Veggie-Hack", note: "z. B. Rügenwalder · oder leichtes Hack" },
      { amount: "4 Scheiben", name: "Schmelzkäse" },
      { amount: "50 g", name: "Gewürzgurken" },
      { amount: "80 ml", name: "Mandelmilch", note: "für die Burger-Sauce" },
      { amount: "50 ml", name: "passierte Tomaten", note: "für die Burger-Sauce" },
      { amount: "etwas", name: "Light-Ketchup", note: "optional · für die Sauce" },
      { amount: "60 g", name: "MORE Sahne Protein", note: "für die Burger-Sauce" },
      { amount: "Salz", name: "& MORE Italian Allrounder" },
      { amount: "1 EL", name: "MORE Light Gourmet Sauce", note: "Burger Sauce · optional" },
    ],
    steps: [
      "Gekochte Kartoffeln pellen, vierteln und in eine Auflaufform geben.",
      "Hack mit etwas Ölspray anbraten und auf den Kartoffeln verteilen.",
      "Sauce separat anrühren (Mandelmilch, Tomaten, optional Ketchup, Sahne Protein, Gewürze), abschmecken und auf dem Hack verstreichen.",
      "Mit Schmelzkäse und Gewürzgurken toppen, bei 175 °C Umluft ca. 15 Min überbacken — fertig!",
    ],
    nutrition: {
      kcal: 683,
      protein: 53,
      carbs: 69,
      fat: 25,
      fiber: 8,
    },
    sourceUrl: "https://www.instagram.com/reel/DUoK7j1jtnd/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },
  {
    slug: "langos-airfryer-flammkuchen",
    packSlug: "feierabend-klassiker",
    number: 7,
    title: "Langos im Airfryer · Flammkuchen-Style",
    subtitle: "1 Langos · 442 kcal · 37 g Protein · 10 Min",
    description:
      "Knuspriger Dinkel-Magerquark-Teig mit cremigem Frischkäse, Schinken-Würfeln und Frühlingszwiebeln — die perfekte kleine WPF-Mahlzeit aus dem Airfryer.",
    prepTime: 5,
    cookTime: 15,
    difficulty: "Einfach",
    servings: 1,
    tags: ["High-Protein", "WPF-Mahlzeit", "Airfryer"],
    ingredients: [
      { amount: "70 g", name: "Dinkelmehl", note: "Teig" },
      { amount: "30 g", name: "MORE Sahne Protein", note: "Teig" },
      { amount: "4 g", name: "Backpulver", note: "Teig" },
      { amount: "etwas", name: "Salz", note: "Teig" },
      { amount: "50 g", name: "Magerquark", note: "Teig" },
      { amount: "ca. 40 ml", name: "Wasser", note: "Teig" },
      { amount: "2 Sprüher", name: "Ölspray", note: "Teig" },
      { amount: "40 g", name: "Exquisa fitline", note: "Topping" },
      { amount: "Gewürze", name: "z. B. MORE Knobilicious · Topping" },
      { amount: "15–20 g", name: "Schinken-Würfel", note: "Topping · z. B. Veggie von Billie Green" },
      { amount: "1/4", name: "rote Zwiebel", note: "Topping" },
      { amount: "Frühlingszwiebeln", name: "Topping" },
    ],
    steps: [
      "Alle trockenen Zutaten für den Teig vermengen, dann mit Magerquark und Wasser verkneten und zu einem Fladen formen.",
      "Frischkäse mit etwas Wasser cremig rühren und den Fladen damit toppen.",
      "Mit roten Zwiebeln und Schinken-Würfeln abschließen und 15 Min bei ca. 130 °C in den Airfryer geben.",
      "Mit Frühlingszwiebeln abschließen und noch warm genießen!",
    ],
    nutrition: {
      kcal: 442,
      protein: 37,
      carbs: 60,
      fat: 6,
      fiber: 6,
    },
    sourceUrl: "https://www.instagram.com/reel/DUfO5PCDImH/",
    sourceLabel: "Original-Reel @bienesfitlife",
  },

  // ─── Pack 2: Bienes Backwelt (8 Rezepte) ───
  {
    slug: "magerquark-kaesekuchen",
    packSlug: "bienes-backwelt",
    number: 1,
    title: "Magerquark-Käsekuchen",
    subtitle: "Cremig, fluffig, 380 kcal",
    description:
      "Bienes Signatur-Käsekuchen — ohne Boden, mit Zitrone und Vanille. Perfektes High-Protein Dessert.",
    prepTime: 15,
    cookTime: 50,
    difficulty: "Einfach",
    servings: 8,
    tags: ["High-Protein", "Ohne Mehl", "Glutenfrei"],
    ingredients: [
      { amount: "1 kg", name: "Magerquark" },
      { amount: "4", name: "Eier" },
      { amount: "60 g", name: "Erythrit" },
      { amount: "30 g", name: "Vanille-Whey" },
      { amount: "1", name: "Zitrone", note: "Saft & Schale" },
      { amount: "30 g", name: "Speisestärke" },
      { amount: "1 Päckchen", name: "Vanillezucker", note: "Light" },
    ],
    steps: [
      "Quark, Eier, Erythrit, Whey und Stärke in einer Schüssel cremig rühren.",
      "Zitronenschale und Saft unterrühren, in eine Springform geben (24 cm).",
      "Bei 160 °C Ober-/Unterhitze 50 Minuten backen, danach im Ofen abkühlen lassen.",
      "Mindestens 2 Stunden kühlen, vor dem Servieren mit Vanillezucker bestäuben.",
    ],
    nutrition: {
      kcal: 180,
      protein: 22,
      carbs: 9,
      fat: 5,
      sugar: 4,
    },
  },
  {
    slug: "schoko-brownies",
    packSlug: "bienes-backwelt",
    number: 2,
    title: "Schoko-Brownies",
    subtitle: "Saftig, schokoladig, 12 g Eiweiß",
    description:
      "Mit Magerquark, Kakao und Bohnenpüree — der saftigste Brownie unter 200 kcal pro Stück.",
    prepTime: 10,
    cookTime: 25,
    difficulty: "Einfach",
    servings: 9,
    tags: ["High-Protein", "Versteckte Bohnen"],
    ingredients: [
      { amount: "400 g", name: "schwarze Bohnen", note: "abgetropft" },
      { amount: "3", name: "Eier" },
      { amount: "100 g", name: "Magerquark" },
      { amount: "60 g", name: "Backkakao" },
      { amount: "60 g", name: "Erythrit" },
      { amount: "30 g", name: "Whey Schoko" },
      { amount: "1 TL", name: "Backpulver" },
      { amount: "50 g", name: "dunkle Schokolade", note: "gehackt" },
    ],
    steps: [
      "Alle Zutaten außer Schokolade im Mixer zu einem glatten Teig pürieren.",
      "Schokoladenstücke unterheben.",
      "In eine quadratische Form (20×20 cm) geben, bei 175 °C 25 Minuten backen.",
      "Auskühlen lassen, in 9 Stücke schneiden.",
    ],
    nutrition: {
      kcal: 165,
      protein: 12,
      carbs: 14,
      fat: 5,
      fiber: 6,
    },
  },
  {
    slug: "biskuitrolle-beeren",
    packSlug: "bienes-backwelt",
    number: 3,
    title: "Biskuitrolle mit Beeren",
    subtitle: "Luftig, fruchtig, ohne Mehl",
    description:
      "Quark-Whey-Biskuit mit fruchtiger Beerenfüllung — leicht, sommerlich, unter 180 kcal pro Stück.",
    prepTime: 20,
    cookTime: 12,
    difficulty: "Mittel",
    servings: 8,
    tags: ["High-Protein", "Ohne Mehl"],
    ingredients: [
      { amount: "4", name: "Eier", note: "getrennt" },
      { amount: "30 g", name: "Vanille-Whey" },
      { amount: "30 g", name: "Speisestärke" },
      { amount: "20 g", name: "Erythrit" },
      { amount: "250 g", name: "Magerquark" },
      { amount: "200 g", name: "gemischte Beeren" },
      { amount: "1 EL", name: "Erythrit" },
      { amount: "1 TL", name: "Vanille" },
    ],
    steps: [
      "Eiweiß steif schlagen. Eigelb mit Whey, Stärke und Erythrit cremig schlagen, Eiweiß unterheben.",
      "Auf einem Backblech glatt streichen, bei 180 °C 10 Minuten backen.",
      "Sofort auf ein feuchtes Tuch stürzen, vorsichtig aufrollen, abkühlen lassen.",
      "Quark mit Erythrit und Vanille verrühren, Beeren unterheben.",
      "Aufrollen, kühlen, vor dem Servieren mit Beeren garnieren.",
    ],
    nutrition: {
      kcal: 175,
      protein: 18,
      carbs: 12,
      fat: 4,
      sugar: 6,
    },
  },
  {
    slug: "cinnamon-rolls",
    packSlug: "bienes-backwelt",
    number: 4,
    title: "Cinnamon Rolls",
    subtitle: "Fluffig, zimtig, 260 kcal pro Stück",
    description:
      "Hefeteig mit Magerquark, Zimt-Erythrit-Füllung und cremigem Frischkäse-Topping.",
    prepTime: 30,
    cookTime: 25,
    difficulty: "Aufwendig",
    servings: 8,
    tags: ["Sonntag-Backen", "High-Protein"],
    ingredients: [
      { amount: "300 g", name: "Magerquark" },
      { amount: "300 g", name: "Mehl Type 405" },
      { amount: "1 Würfel", name: "Frische Hefe" },
      { amount: "1", name: "Ei" },
      { amount: "30 g", name: "Erythrit" },
      { amount: "100 g", name: "Frischkäse light" },
      { amount: "30 g", name: "Erythrit-Puder" },
      { amount: "2 EL", name: "Zimt" },
      { amount: "30 g", name: "Erythrit" },
    ],
    steps: [
      "Quark, Mehl, Hefe, Ei und Erythrit zu einem Hefeteig kneten, 30 Minuten gehen lassen.",
      "Auf bemehlter Fläche rechteckig ausrollen, mit Zimt-Erythrit bestreuen.",
      "Aufrollen, in 8 Stücke schneiden, in eine Form setzen.",
      "Bei 180 °C 25 Minuten backen, mit Frischkäse-Topping bestreichen.",
    ],
    nutrition: {
      kcal: 260,
      protein: 14,
      carbs: 38,
      fat: 5,
      sugar: 7,
    },
  },
  {
    slug: "lemon-drizzle-cake",
    packSlug: "bienes-backwelt",
    number: 5,
    title: "Lemon Drizzle Cake",
    subtitle: "Frisch, zitronig, super saftig",
    description:
      "Klassischer englischer Zitronenkuchen — Bienes Version mit Magerquark und Whey statt Butter.",
    prepTime: 15,
    cookTime: 35,
    difficulty: "Einfach",
    servings: 8,
    tags: ["Frühlingsgefühl", "High-Protein"],
    ingredients: [
      { amount: "250 g", name: "Magerquark" },
      { amount: "150 g", name: "Mehl" },
      { amount: "30 g", name: "Vanille-Whey" },
      { amount: "3", name: "Eier" },
      { amount: "60 g", name: "Erythrit" },
      { amount: "2", name: "Bio-Zitronen" },
      { amount: "1 TL", name: "Backpulver" },
      { amount: "30 g", name: "Erythrit-Puder" },
    ],
    steps: [
      "Quark, Eier, Erythrit, Mehl, Whey, Backpulver und Zitronenabrieb verrühren.",
      "In eine Kastenform geben, bei 170 °C 35 Minuten backen.",
      "Aus dem Ofen mehrfach mit einem Spieß einstechen, Zitronensaft mit Erythrit-Puder verrühren und über den heißen Kuchen träufeln.",
    ],
    nutrition: {
      kcal: 210,
      protein: 14,
      carbs: 24,
      fat: 4,
      sugar: 4,
    },
  },
  {
    slug: "pistazien-cheesecake",
    packSlug: "bienes-backwelt",
    number: 6,
    title: "Pistazien-Cheesecake",
    subtitle: "Trendy, nussig, 290 kcal",
    description:
      "Der TikTok-Star als Bienes High-Protein-Version — mit echter Pistaziencreme und Quark.",
    prepTime: 20,
    cookTime: 45,
    difficulty: "Mittel",
    servings: 10,
    tags: ["Trend", "High-Protein", "Pistazien"],
    ingredients: [
      { amount: "150 g", name: "Haferkekse light" },
      { amount: "30 g", name: "Mandelbutter" },
      { amount: "750 g", name: "Magerquark" },
      { amount: "200 g", name: "Frischkäse light" },
      { amount: "3", name: "Eier" },
      { amount: "60 g", name: "Erythrit" },
      { amount: "60 g", name: "Pistaziencreme" },
      { amount: "30 g", name: "Pistazien", note: "gehackt" },
    ],
    steps: [
      "Kekse zerbröseln, mit Mandelbutter mischen, in eine Springform drücken.",
      "Quark, Frischkäse, Eier, Erythrit und Pistaziencreme glatt rühren.",
      "Auf den Boden gießen, bei 160 °C 45 Minuten backen.",
      "Auskühlen lassen, mit gehackten Pistazien dekorieren.",
    ],
    nutrition: {
      kcal: 290,
      protein: 22,
      carbs: 18,
      fat: 14,
      sugar: 5,
    },
  },
  {
    slug: "schoko-lava-cake",
    packSlug: "bienes-backwelt",
    number: 7,
    title: "Schoko Lava Cake",
    subtitle: "Flüssiger Kern, 230 kcal",
    description:
      "Single-Serve Lava Cake aus der Mikrowelle — perfekt für den abendlichen Schoko-Crash.",
    prepTime: 5,
    cookTime: 2,
    difficulty: "Einfach",
    servings: 1,
    tags: ["Quick", "Single-Serve", "High-Protein"],
    ingredients: [
      { amount: "30 g", name: "Schoko-Whey" },
      { amount: "10 g", name: "Backkakao" },
      { amount: "1", name: "Ei" },
      { amount: "50 ml", name: "Milch 1,5 %" },
      { amount: "1 TL", name: "Erythrit" },
      { amount: "1 Stück", name: "Zartbitterschokolade" },
    ],
    steps: [
      "Alle Zutaten außer Schokolade in einer Tasse glatt rühren.",
      "Schokoladenstück in die Mitte drücken.",
      "In der Mikrowelle 1:30–2 Minuten bei 600 W backen, sofort servieren.",
    ],
    nutrition: {
      kcal: 230,
      protein: 32,
      carbs: 14,
      fat: 6,
      sugar: 5,
    },
  },
  {
    slug: "beeren-tarte",
    packSlug: "bienes-backwelt",
    number: 8,
    title: "Beeren-Tarte",
    subtitle: "No-Bake, sommerlich, fruchtig",
    description:
      "Knuspriger Hafer-Mandel-Boden mit Vanille-Quark-Creme und buntem Beerentopping.",
    prepTime: 20,
    cookTime: 0,
    difficulty: "Einfach",
    servings: 8,
    tags: ["No-Bake", "Sommer", "High-Protein"],
    ingredients: [
      { amount: "150 g", name: "Haferflocken" },
      { amount: "60 g", name: "Mandelmus" },
      { amount: "2 EL", name: "Honig" },
      { amount: "500 g", name: "Magerquark" },
      { amount: "200 g", name: "Skyr Vanille" },
      { amount: "30 g", name: "Vanille-Whey" },
      { amount: "300 g", name: "gemischte Beeren" },
    ],
    steps: [
      "Haferflocken, Mandelmus und Honig vermengen, in eine Form drücken, kühlen.",
      "Quark, Skyr und Whey verrühren, auf den Boden geben.",
      "Mit Beeren belegen, mindestens 2 Stunden kühlen.",
    ],
    nutrition: {
      kcal: 245,
      protein: 20,
      carbs: 26,
      fat: 6,
      fiber: 5,
    },
  },

  // ─── Pack 3: Blitz-Snacks (8 Rezepte, je 3 Zutaten) ───
  {
    slug: "protein-fluff",
    packSlug: "blitz-snacks",
    number: 1,
    title: "Protein-Fluff",
    subtitle: "3 Zutaten · 5 Min · 28 g Eiweiß",
    description:
      "Bienes Klassiker für den Heißhunger-Notfall. Magerquark, Wasser, Geschmackspulver — fertig.",
    prepTime: 5,
    difficulty: "Einfach",
    servings: 1,
    tags: ["3 Zutaten", "5 Minuten", "High-Protein"],
    ingredients: [
      { amount: "250 g", name: "Magerquark" },
      { amount: "100 ml", name: "Eiswasser" },
      { amount: "1 EL", name: "Chunky Flavour", note: "Geschmack nach Wahl" },
    ],
    steps: [
      "Magerquark in eine Schüssel geben.",
      "Eiswasser und Chunky Flavour zugeben.",
      "Mit dem Handmixer 3 Minuten auf höchster Stufe schaumig schlagen, bis das Volumen sich verdoppelt.",
    ],
    nutrition: {
      kcal: 165,
      protein: 28,
      carbs: 8,
      fat: 1,
    },
  },
  {
    slug: "bananen-pancakes",
    packSlug: "blitz-snacks",
    number: 2,
    title: "Bananen-Pancakes",
    subtitle: "3 Zutaten · 10 Min · 22 g Eiweiß",
    description:
      "Banane, Eier, Whey — kein Mehl, kein Zucker. Einfacher und besser geht es nicht.",
    prepTime: 5,
    cookTime: 5,
    difficulty: "Einfach",
    servings: 1,
    tags: ["3 Zutaten", "Glutenfrei", "Schnell"],
    ingredients: [
      { amount: "1", name: "reife Banane" },
      { amount: "2", name: "Eier" },
      { amount: "20 g", name: "Vanille-Whey" },
    ],
    steps: [
      "Banane mit der Gabel zerdrücken.",
      "Eier und Whey unterrühren bis ein glatter Teig entsteht.",
      "In einer beschichteten Pfanne kleine Pancakes goldbraun ausbacken.",
    ],
    nutrition: {
      kcal: 320,
      protein: 28,
      carbs: 28,
      fat: 9,
    },
  },
  {
    slug: "magerquark-cup",
    packSlug: "blitz-snacks",
    number: 3,
    title: "Magerquark-Cup",
    subtitle: "3 Zutaten · 2 Min · cremig",
    description:
      "Schichten in der Tasse — Quark, Beeren, Knusperflocken. Frühstück oder Nachmittagssnack.",
    prepTime: 2,
    difficulty: "Einfach",
    servings: 1,
    tags: ["3 Zutaten", "Schnell", "Mealprep-tauglich"],
    ingredients: [
      { amount: "200 g", name: "Magerquark" },
      { amount: "100 g", name: "gemischte Beeren" },
      { amount: "20 g", name: "Knuspermüsli" },
    ],
    steps: [
      "Quark in eine Tasse oder ein Glas geben.",
      "Beeren darüber verteilen.",
      "Mit Knuspermüsli toppen, sofort servieren.",
    ],
    nutrition: {
      kcal: 220,
      protein: 22,
      carbs: 22,
      fat: 3,
    },
  },
  {
    slug: "erdnussbutter-bites",
    packSlug: "blitz-snacks",
    number: 4,
    title: "Erdnussbutter-Bites",
    subtitle: "3 Zutaten · 10 Min · 8 g Eiweiß",
    description:
      "Datteln, Erdnussbutter, Whey — gerollt, gekühlt, verputzt. Energie für unterwegs.",
    prepTime: 10,
    difficulty: "Einfach",
    servings: 8,
    tags: ["3 Zutaten", "On-the-Go"],
    ingredients: [
      { amount: "150 g", name: "Datteln", note: "entsteint" },
      { amount: "60 g", name: "Erdnussbutter natur" },
      { amount: "30 g", name: "Vanille-Whey" },
    ],
    steps: [
      "Datteln im Mixer fein hacken.",
      "Erdnussbutter und Whey zugeben, zu einer klebrigen Masse mixen.",
      "8 Kugeln formen, in den Kühlschrank stellen, 30 Minuten fest werden lassen.",
    ],
    nutrition: {
      kcal: 110,
      protein: 8,
      carbs: 12,
      fat: 4,
      fiber: 1,
    },
  },
  {
    slug: "schoko-mousse-express",
    packSlug: "blitz-snacks",
    number: 5,
    title: "Schoko-Mousse Express",
    subtitle: "3 Zutaten · 5 Min · cremig",
    description:
      "Schoko-Whey, Magerquark, Skyr — fluffig wie eine echte Mousse, aber mit 30 g Eiweiß.",
    prepTime: 5,
    difficulty: "Einfach",
    servings: 1,
    tags: ["3 Zutaten", "Dessert", "High-Protein"],
    ingredients: [
      { amount: "200 g", name: "Magerquark" },
      { amount: "100 g", name: "Skyr Natur" },
      { amount: "20 g", name: "Schoko-Whey" },
    ],
    steps: [
      "Alle Zutaten in eine Schüssel geben.",
      "Mit dem Handmixer 2 Minuten luftig schlagen.",
      "In ein Glas füllen, optional mit Kakao bestäuben.",
    ],
    nutrition: {
      kcal: 240,
      protein: 32,
      carbs: 14,
      fat: 3,
    },
  },
  {
    slug: "cookie-dough",
    packSlug: "blitz-snacks",
    number: 6,
    title: "Cookie-Dough",
    subtitle: "3 Zutaten · 5 Min · 14 g Eiweiß",
    description:
      "Roher Keksteig — nur dass dieser komplett gesund ist. Aus Kichererbsen-Mehl, Whey, Schokoladenstücken.",
    prepTime: 5,
    difficulty: "Einfach",
    servings: 2,
    tags: ["3 Zutaten", "Vegan-möglich"],
    ingredients: [
      { amount: "100 g", name: "Magerquark" },
      { amount: "30 g", name: "Vanille-Whey" },
      { amount: "20 g", name: "Schokostücke" },
    ],
    steps: [
      "Quark und Whey verrühren, bis ein dicker Teig entsteht.",
      "Schokostücke unterheben.",
      "Mit dem Löffel direkt aus der Schüssel essen.",
    ],
    nutrition: {
      kcal: 200,
      protein: 22,
      carbs: 14,
      fat: 5,
    },
  },
  {
    slug: "eis-bites",
    packSlug: "blitz-snacks",
    number: 7,
    title: "Eis-Bites",
    subtitle: "3 Zutaten · TK · sommerfrisch",
    description:
      "Skyr, Beeren, Schoko — auf Backpapier eingefroren, in Stücke gebrochen. Zucker-frei naschen.",
    prepTime: 10,
    difficulty: "Einfach",
    servings: 6,
    tags: ["3 Zutaten", "TK", "Sommer"],
    ingredients: [
      { amount: "300 g", name: "Skyr Vanille" },
      { amount: "100 g", name: "gemischte Beeren" },
      { amount: "20 g", name: "Zartbitterschokolade", note: "geraspelt" },
    ],
    steps: [
      "Skyr auf Backpapier verstreichen (ca. 1 cm dick).",
      "Beeren und Schokoraspel darüber verteilen.",
      "Mindestens 4 Stunden einfrieren, in Stücke brechen.",
    ],
    nutrition: {
      kcal: 90,
      protein: 8,
      carbs: 9,
      fat: 2,
    },
  },
  {
    slug: "quark-riegel",
    packSlug: "blitz-snacks",
    number: 8,
    title: "Quark-Riegel",
    subtitle: "3 Zutaten · 15 Min · TK-tauglich",
    description:
      "Magerquark, Haferflocken, Honig — gepresst, gekühlt, in Riegel geschnitten. Mealprep-Snack.",
    prepTime: 15,
    difficulty: "Einfach",
    servings: 6,
    tags: ["3 Zutaten", "Mealprep", "Snack"],
    ingredients: [
      { amount: "300 g", name: "Magerquark" },
      { amount: "150 g", name: "Haferflocken zart" },
      { amount: "2 EL", name: "Honig" },
    ],
    steps: [
      "Alle Zutaten vermischen, in eine kleine Form drücken.",
      "Mindestens 2 Stunden kühlen.",
      "In 6 Riegel schneiden.",
    ],
    nutrition: {
      kcal: 150,
      protein: 14,
      carbs: 22,
      fat: 2,
      fiber: 3,
    },
  },

  // ─── Pack 4: Volumen-Wunder (6 Rezepte) ───
  {
    slug: "riesen-zucchini-pfanne",
    packSlug: "volumen-wunder",
    number: 1,
    title: "Riesen-Zucchini-Pfanne",
    subtitle: "950 g Portion · nur 380 kcal",
    description:
      "Zucchini-Spaghetti mit Putenstreifen, Cherrytomaten und Pesto — eine riesige Portion ohne Reue.",
    prepTime: 15,
    cookTime: 15,
    difficulty: "Einfach",
    servings: 1,
    tags: ["Volumen", "Low-Carb", "High-Protein"],
    ingredients: [
      { amount: "2", name: "große Zucchini", note: "spiralisiert" },
      { amount: "200 g", name: "Putenbrust", note: "in Streifen" },
      { amount: "200 g", name: "Cherrytomaten" },
      { amount: "1 EL", name: "grünes Pesto" },
      { amount: "30 g", name: "Parmesan" },
      { amount: "Kräuter", name: "frisch" },
    ],
    steps: [
      "Putenstreifen in einer beschichteten Pfanne anbraten.",
      "Cherrytomaten zugeben, kurz mitbraten.",
      "Zucchini-Spaghetti dazugeben, 3 Minuten schwenken.",
      "Pesto unterrühren, mit Parmesan und Kräutern toppen.",
    ],
    nutrition: {
      kcal: 380,
      protein: 50,
      carbs: 18,
      fat: 12,
      fiber: 8,
    },
  },
  {
    slug: "xxl-haehnchensalat",
    packSlug: "volumen-wunder",
    number: 2,
    title: "XXL-Hähnchensalat",
    subtitle: "1100 g Portion · 450 kcal",
    description:
      "Eine ganze Schüssel voll Salat, Hähnchen, Avocado und Mais — Caesar-Style mit Joghurt-Dressing.",
    prepTime: 15,
    cookTime: 10,
    difficulty: "Einfach",
    servings: 1,
    tags: ["Volumen", "High-Protein"],
    ingredients: [
      { amount: "200 g", name: "Hähnchenbrust" },
      { amount: "150 g", name: "Römersalat" },
      { amount: "100 g", name: "Cherrytomaten" },
      { amount: "1/2", name: "Avocado" },
      { amount: "100 g", name: "Mais" },
      { amount: "100 g", name: "Magerjoghurt" },
      { amount: "1 TL", name: "Senf" },
      { amount: "1 TL", name: "Honig" },
    ],
    steps: [
      "Hähnchen würzen, beidseitig 4 Minuten braten, ruhen lassen, in Streifen schneiden.",
      "Salat, Tomaten, Avocado und Mais in eine Schüssel geben.",
      "Joghurt mit Senf und Honig verrühren, über den Salat geben.",
      "Hähnchen oben drauf, sofort servieren.",
    ],
    nutrition: {
      kcal: 450,
      protein: 52,
      carbs: 32,
      fat: 14,
      fiber: 11,
    },
  },
  {
    slug: "kohlsuppe-premium",
    packSlug: "volumen-wunder",
    number: 3,
    title: "Kohlsuppe Premium",
    subtitle: "1500 ml · nur 280 kcal",
    description:
      "Die berühmte Kohlsuppe — aber mit Putenwürfeln und Kichererbsen, damit Sättigung garantiert ist.",
    prepTime: 15,
    cookTime: 30,
    difficulty: "Einfach",
    servings: 2,
    tags: ["Volumen", "Suppe", "Mealprep"],
    ingredients: [
      { amount: "500 g", name: "Weißkohl" },
      { amount: "200 g", name: "Putenbrust", note: "gewürfelt" },
      { amount: "1 Dose", name: "Kichererbsen" },
      { amount: "2", name: "Karotten" },
      { amount: "1", name: "Zwiebel" },
      { amount: "800 ml", name: "Gemüsebrühe" },
      { amount: "1 EL", name: "Tomatenmark" },
      { amount: "Kümmel", name: "& Pfeffer" },
    ],
    steps: [
      "Zwiebel und Karotten anschwitzen, Putenwürfel zugeben und anbraten.",
      "Kohl klein schneiden, mit Tomatenmark, Brühe und Kümmel zugeben.",
      "20 Minuten köcheln lassen, Kichererbsen zugeben, weitere 5 Minuten kochen.",
    ],
    nutrition: {
      kcal: 280,
      protein: 35,
      carbs: 24,
      fat: 4,
      fiber: 12,
    },
  },
  {
    slug: "pilzpfanne-quark",
    packSlug: "volumen-wunder",
    number: 4,
    title: "Pilzpfanne mit Quark",
    subtitle: "850 g Portion · 350 kcal",
    description:
      "Champignons mit Tofu und Kräuter-Quark — riesige Portion, trotzdem leicht.",
    prepTime: 10,
    cookTime: 12,
    difficulty: "Einfach",
    servings: 1,
    tags: ["Volumen", "Vegetarisch"],
    ingredients: [
      { amount: "400 g", name: "Champignons" },
      { amount: "150 g", name: "Räuchertofu", note: "gewürfelt" },
      { amount: "200 g", name: "Magerquark" },
      { amount: "Kräuter", name: "frisch" },
      { amount: "1", name: "Knoblauchzehe" },
      { amount: "Salz", name: "& Pfeffer" },
    ],
    steps: [
      "Pilze und Tofu in einer Pfanne goldbraun braten.",
      "Knoblauch zugeben, kurz mitbraten.",
      "Quark mit Kräutern verrühren, neben die Pfanne servieren oder unterheben.",
    ],
    nutrition: {
      kcal: 350,
      protein: 42,
      carbs: 18,
      fat: 11,
      fiber: 6,
    },
  },
  {
    slug: "asia-veggie-bowl",
    packSlug: "volumen-wunder",
    number: 5,
    title: "Asia-Veggie-Bowl",
    subtitle: "1000 g · 420 kcal",
    description:
      "Brokkoli, Edamame, Karotten, Reis und Hähnchen mit asiatischem Sesam-Dressing.",
    prepTime: 15,
    cookTime: 10,
    difficulty: "Einfach",
    servings: 1,
    tags: ["Volumen", "Asia"],
    ingredients: [
      { amount: "150 g", name: "Hähnchenbrust" },
      { amount: "200 g", name: "Brokkoli" },
      { amount: "100 g", name: "Edamame" },
      { amount: "100 g", name: "Karotten" },
      { amount: "100 g", name: "Reis", note: "gekocht" },
      { amount: "1 EL", name: "Sojasauce" },
      { amount: "1 TL", name: "Sesamöl" },
      { amount: "1 TL", name: "Sesam" },
    ],
    steps: [
      "Hähnchen in Streifen schneiden und braten.",
      "Brokkoli und Karotten dampfgaren.",
      "Alles in einer Schüssel anrichten, mit Sojasauce, Sesamöl und Sesam beträufeln.",
    ],
    nutrition: {
      kcal: 420,
      protein: 45,
      carbs: 38,
      fat: 8,
      fiber: 9,
    },
  },
  {
    slug: "suesskartoffel-schale",
    packSlug: "volumen-wunder",
    number: 6,
    title: "Süßkartoffel-Schale",
    subtitle: "950 g · 460 kcal",
    description:
      "Gefüllte Süßkartoffel mit Pulled Hähnchen, Avocado und Joghurt-Limetten-Sauce.",
    prepTime: 10,
    cookTime: 40,
    difficulty: "Einfach",
    servings: 1,
    tags: ["Volumen", "Mealprep-tauglich"],
    ingredients: [
      { amount: "1", name: "große Süßkartoffel" },
      { amount: "200 g", name: "Hähnchenbrust" },
      { amount: "1/2", name: "Avocado" },
      { amount: "100 g", name: "Magerjoghurt" },
      { amount: "1", name: "Limette" },
      { amount: "Koriander", name: "frisch" },
    ],
    steps: [
      "Süßkartoffel im Ofen 40 Minuten bei 200 °C backen.",
      "Hähnchen kochen, dann mit zwei Gabeln zerzupfen.",
      "Süßkartoffel aufschneiden, mit Pulled Hähnchen und Avocado füllen.",
      "Joghurt mit Limettensaft verrühren, drüber geben, mit Koriander toppen.",
    ],
    nutrition: {
      kcal: 460,
      protein: 48,
      carbs: 42,
      fat: 10,
      fiber: 9,
    },
  },

  // ─── Pack 5: Meal-Prep Heroes (7 Rezepte) ───
  {
    slug: "schoko-overnight-oats",
    packSlug: "meal-prep-heroes",
    number: 1,
    title: "Schoko-Overnight-Oats",
    subtitle: "Vorbereitet · 28 g Eiweiß",
    description:
      "Über Nacht eingeweicht, morgens fertig — Haferflocken, Schoko-Whey und Beeren in der Glasdose.",
    prepTime: 5,
    difficulty: "Einfach",
    servings: 1,
    tags: ["Mealprep", "Frühstück"],
    ingredients: [
      { amount: "60 g", name: "Haferflocken" },
      { amount: "200 ml", name: "Mandelmilch" },
      { amount: "30 g", name: "Schoko-Whey" },
      { amount: "100 g", name: "Beeren" },
      { amount: "1 TL", name: "Chiasamen" },
    ],
    steps: [
      "Alle Zutaten in ein Weckglas geben, gut vermengen.",
      "Über Nacht in den Kühlschrank stellen.",
      "Morgens umrühren, optional mit weiteren Beeren toppen.",
    ],
    nutrition: {
      kcal: 380,
      protein: 32,
      carbs: 42,
      fat: 7,
      fiber: 8,
    },
  },
  {
    slug: "fuenf-schicht-salat",
    packSlug: "meal-prep-heroes",
    number: 2,
    title: "5-Schicht-Salat",
    subtitle: "Vorbereitet · hält 4 Tage",
    description:
      "Quinoa, Hähnchen, Kichererbsen, Gemüse und Joghurt-Dressing — alles in einem Glas geschichtet.",
    prepTime: 20,
    cookTime: 10,
    difficulty: "Einfach",
    servings: 4,
    tags: ["Mealprep", "Salat"],
    ingredients: [
      { amount: "200 g", name: "Quinoa", note: "gekocht" },
      { amount: "400 g", name: "Hähnchenbrust" },
      { amount: "1 Dose", name: "Kichererbsen" },
      { amount: "200 g", name: "Cherrytomaten" },
      { amount: "1", name: "Gurke" },
      { amount: "200 g", name: "Magerjoghurt" },
      { amount: "1 EL", name: "Olivenöl" },
      { amount: "Zitrone", name: "& Kräuter" },
    ],
    steps: [
      "Hähnchen würfeln und braten.",
      "Joghurt mit Olivenöl, Zitrone und Kräutern zu einem Dressing verrühren.",
      "In 4 Gläsern schichten: Dressing → Quinoa → Hähnchen → Kichererbsen → Tomaten/Gurke.",
      "Im Kühlschrank lagern, vor dem Verzehr durchschütteln.",
    ],
    nutrition: {
      kcal: 420,
      protein: 38,
      carbs: 40,
      fat: 10,
      fiber: 9,
    },
  },
  {
    slug: "asia-bowl-meal-prep",
    packSlug: "meal-prep-heroes",
    number: 3,
    title: "Asia-Bowl Meal Prep",
    subtitle: "Vorbereitet · für 4 Tage",
    description:
      "Reis, Edamame, Tofu und Sesam — vorbereitet für die ganze Woche, mit pikantem Erdnuss-Dressing.",
    prepTime: 20,
    cookTime: 15,
    difficulty: "Einfach",
    servings: 4,
    tags: ["Mealprep", "Asia", "Vegetarisch"],
    ingredients: [
      { amount: "300 g", name: "Reis", note: "gekocht" },
      { amount: "300 g", name: "Räuchertofu" },
      { amount: "200 g", name: "Edamame" },
      { amount: "2", name: "Karotten" },
      { amount: "60 g", name: "Erdnussbutter" },
      { amount: "2 EL", name: "Sojasauce" },
      { amount: "1 EL", name: "Limettensaft" },
    ],
    steps: [
      "Tofu würfeln und knusprig braten.",
      "Karotten julienneartig schneiden.",
      "Erdnussbutter, Sojasauce und Limettensaft zu einem Dressing verrühren.",
      "In 4 Boxen schichten: Reis, Tofu, Edamame, Karotten — Dressing extra.",
    ],
    nutrition: {
      kcal: 480,
      protein: 32,
      carbs: 50,
      fat: 16,
      fiber: 8,
    },
  },
  {
    slug: "reis-bowl-curry",
    packSlug: "meal-prep-heroes",
    number: 4,
    title: "Reis-Bowl Curry",
    subtitle: "Vorbereitet · 32 g Eiweiß",
    description:
      "Mildes Hähnchen-Curry mit Kokosmilch und Reis — wärmt schön von innen, perfekt für die Mittagspause.",
    prepTime: 15,
    cookTime: 25,
    difficulty: "Einfach",
    servings: 4,
    tags: ["Mealprep", "Curry"],
    ingredients: [
      { amount: "500 g", name: "Hähnchenbrust" },
      { amount: "400 ml", name: "Kokosmilch light" },
      { amount: "2 EL", name: "Currypaste mild" },
      { amount: "300 g", name: "Reis", note: "gekocht" },
      { amount: "2", name: "Paprika" },
      { amount: "1", name: "Zwiebel" },
      { amount: "Koriander", name: "frisch" },
    ],
    steps: [
      "Zwiebel und Paprika anbraten.",
      "Hähnchen würfeln, zugeben, mit Currypaste anrösten.",
      "Mit Kokosmilch ablöschen, 15 Minuten köcheln lassen.",
      "Mit Reis in 4 Boxen verteilen, mit Koriander garnieren.",
    ],
    nutrition: {
      kcal: 510,
      protein: 42,
      carbs: 48,
      fat: 13,
      fiber: 5,
    },
  },
  {
    slug: "bulgur-salat",
    packSlug: "meal-prep-heroes",
    number: 5,
    title: "Bulgur-Salat",
    subtitle: "Vorbereitet · vegetarisch · sättigend",
    description:
      "Bulgur, Feta, Granatapfel und viel Petersilie — orientalisch inspiriert und super frisch.",
    prepTime: 15,
    difficulty: "Einfach",
    servings: 4,
    tags: ["Mealprep", "Vegetarisch", "Mediterran"],
    ingredients: [
      { amount: "200 g", name: "Bulgur" },
      { amount: "200 g", name: "Feta light" },
      { amount: "1", name: "Granatapfel" },
      { amount: "1 Bund", name: "Petersilie" },
      { amount: "1", name: "Gurke" },
      { amount: "2 EL", name: "Olivenöl" },
      { amount: "1", name: "Zitrone" },
    ],
    steps: [
      "Bulgur nach Packungsanleitung kochen, abkühlen lassen.",
      "Feta würfeln, Granatapfelkerne, gehackte Petersilie und Gurke zugeben.",
      "Mit Olivenöl, Zitronensaft, Salz und Pfeffer abschmecken.",
      "In 4 Boxen verteilen, hält 4 Tage im Kühlschrank.",
    ],
    nutrition: {
      kcal: 380,
      protein: 18,
      carbs: 42,
      fat: 14,
      fiber: 8,
    },
  },
  {
    slug: "quinoa-box",
    packSlug: "meal-prep-heroes",
    number: 6,
    title: "Quinoa-Power-Box",
    subtitle: "Vorbereitet · 38 g Eiweiß",
    description:
      "Quinoa, Süßkartoffel, Lachs und Spinat in einer Box — Omega-3 für die Bürowoche.",
    prepTime: 15,
    cookTime: 25,
    difficulty: "Mittel",
    servings: 4,
    tags: ["Mealprep", "Omega-3"],
    ingredients: [
      { amount: "200 g", name: "Quinoa" },
      { amount: "2", name: "Süßkartoffeln" },
      { amount: "400 g", name: "Lachsfilet" },
      { amount: "200 g", name: "Babyspinat" },
      { amount: "1", name: "Zitrone" },
      { amount: "1 EL", name: "Olivenöl" },
    ],
    steps: [
      "Süßkartoffeln würfeln und 25 Minuten bei 200 °C rösten.",
      "Quinoa kochen, Lachs in der Pfanne braten.",
      "In 4 Boxen schichten: Quinoa, Süßkartoffel, Spinat, Lachs.",
      "Mit Zitronenscheibe und Olivenöl-Drizzle servieren.",
    ],
    nutrition: {
      kcal: 520,
      protein: 38,
      carbs: 48,
      fat: 18,
      fiber: 8,
    },
  },
  {
    slug: "haehnchen-wraps",
    packSlug: "meal-prep-heroes",
    number: 7,
    title: "Hähnchen-Wraps",
    subtitle: "Vorbereitet · handlich · 35 g Eiweiß",
    description:
      "Vollkorn-Wraps mit Hähnchen, Avocado, Salat und Joghurt-Sauce — fertig zum Einpacken.",
    prepTime: 15,
    cookTime: 10,
    difficulty: "Einfach",
    servings: 4,
    tags: ["Mealprep", "Handheld"],
    ingredients: [
      { amount: "4", name: "Vollkorn-Wraps" },
      { amount: "400 g", name: "Hähnchenbrust" },
      { amount: "1", name: "Avocado" },
      { amount: "Salat", name: "nach Wahl" },
      { amount: "200 g", name: "Magerjoghurt" },
      { amount: "1 TL", name: "Senf" },
    ],
    steps: [
      "Hähnchen würzen, in Streifen braten, abkühlen lassen.",
      "Joghurt mit Senf verrühren, auf den Wraps verstreichen.",
      "Hähnchen, Avocado-Scheiben und Salat darauf verteilen.",
      "Fest aufrollen, in Folie einwickeln, hält 2 Tage.",
    ],
    nutrition: {
      kcal: 410,
      protein: 38,
      carbs: 35,
      fat: 13,
      fiber: 6,
    },
  },
];

export function getRecipesForPack(packSlug: string): Recipe[] {
  return recipes
    .filter((recipe) => recipe.packSlug === packSlug)
    .sort((a, b) => a.number - b.number);
}

export function getRecipe(packSlug: string, recipeSlug: string): Recipe | undefined {
  return recipes.find(
    (recipe) => recipe.packSlug === packSlug && recipe.slug === recipeSlug
  );
}
