// One-shot script: calls Gemini for every static recipe and writes the
// resulting micros to lib/recipe-micros.ts (committed, no runtime cost).
//
// Run: GEMINI_API_KEY=... npx tsx --tsconfig ./tsconfig.json scripts/generate-static-micros.ts
//
// Re-runs are safe: previously-generated entries are reused unless --force is
// passed, so iterating on individual recipes doesn't burn quota.

import fs from "node:fs/promises";
import path from "node:path";
import { recipes } from "../lib/recipes";
import type { Micronutrient } from "../lib/recipes";
import { generateMicros } from "../lib/ai/generate-micros";

const OUT_PATH = path.join(process.cwd(), "lib", "recipe-micros.ts");
const FORCE = process.argv.includes("--force");

type MicrosMap = Record<string, Micronutrient[]>;

async function loadExisting(): Promise<MicrosMap> {
  try {
    const src = await fs.readFile(OUT_PATH, "utf8");
    // Pull out the JSON-like literal between `= {` and the matching closing
    // `}` followed by either `as const;` or `as const satisfies ...;`.
    const match = src.match(
      /export const recipeMicros[^=]*=\s*({[\s\S]*?})\s*as const(?:\s+satisfies\s+[^;]+)?;/
    );
    if (!match) return {};
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const obj: any = new Function("return " + match[1])();
    return obj as MicrosMap;
  } catch {
    return {};
  }
}

function emitFile(map: MicrosMap): string {
  const sortedKeys = Object.keys(map).sort();
  const entries = sortedKeys
    .map((slug) => {
      const items = map[slug]
        .map(
          (m) =>
            `    { name: ${JSON.stringify(m.name)}, amount: ${JSON.stringify(
              m.amount
            )}, pctDaily: ${m.pctDaily ?? 0} },`
        )
        .join("\n");
      return `  ${JSON.stringify(slug)}: [\n${items}\n  ],`;
    })
    .join("\n");

  return `// Auto-generated by scripts/generate-static-micros.ts.
// Mikronährstoffe pro Portion, von Gemini 2.5 Flash aus den Zutaten abgeleitet.
// Manuelle Edits werden beim nächsten Skript-Lauf überschrieben.
//
// Re-generieren: \`npx tsx scripts/generate-static-micros.ts\` (--force für alle)

import type { Micronutrient } from "./recipes";

export const recipeMicros: Record<string, Micronutrient[]> = {
${entries}
} as const satisfies Record<string, Micronutrient[]>;
`;
}

async function main() {
  if (!process.env.GEMINI_API_KEY) {
    console.error("✗ GEMINI_API_KEY not set");
    process.exit(1);
  }

  const existing = FORCE ? {} : await loadExisting();
  const todo = recipes.filter((r) => !existing[r.slug]);
  const result: MicrosMap = { ...existing };

  console.log(
    `\n→ Generating micros via Gemini 2.5 Flash`
  );
  console.log(
    `  Total recipes: ${recipes.length}  |  Already cached: ${
      recipes.length - todo.length
    }  |  To generate: ${todo.length}\n`
  );

  for (let i = 0; i < todo.length; i++) {
    const r = todo[i];
    const idx = `${i + 1}/${todo.length}`;
    process.stdout.write(`  [${idx}] ${r.title}  …`);
    const start = Date.now();
    try {
      const micros = await generateMicros(r);
      result[r.slug] = micros;
      const ms = Date.now() - start;
      console.log(` ✓ ${micros.length} micros · ${ms}ms`);
      // Persist after each so a crash doesn't lose the batch
      await fs.writeFile(OUT_PATH, emitFile(result), "utf8");
    } catch (err) {
      console.log(` ✗ ${(err as Error).message}`);
    }
    // Light rate-limit cushion (Flash free tier ≈ 60 RPM)
    if (i < todo.length - 1) await new Promise((r) => setTimeout(r, 400));
  }

  console.log(`\n✓ Wrote ${Object.keys(result).length} entries to ${OUT_PATH}\n`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
